const flags = [
    { country: "Afghanistan", img: "https://flagcdn.com/af.svg" },
    { country: "Ålandinseln", img: "https://flagcdn.com/ax.svg" },
    { country: "Albanien", img: "https://flagcdn.com/al.svg" },
    { country: "Algerien", img: "https://flagcdn.com/dz.svg" },
    { country: "Amerikanisch-Samoa", img: "https://flagcdn.com/as.svg" },
    { country: "Andorra", img: "https://flagcdn.com/ad.svg" },
    { country: "Angola", img: "https://flagcdn.com/ao.svg" },
    { country: "Anguilla", img: "https://flagcdn.com/ai.svg" },
    { country: "Antarktis", img: "https://flagcdn.com/aq.svg" },
    { country: "Antigua und Barbuda", img: "https://flagcdn.com/ag.svg" },
    { country: "Argentinien", img: "https://flagcdn.com/ar.svg" },
    { country: "Armenien", img: "https://flagcdn.com/am.svg" },
    { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
    { country: "Australien", img: "https://flagcdn.com/au.svg" },
    { country: "Österreich", img: "https://flagcdn.com/at.svg" },
    { country: "Aserbaidschan", img: "https://flagcdn.com/az.svg" },
    { country: "Bahamas", img: "https://flagcdn.com/bs.svg" },
    { country: "Bahrain", img: "https://flagcdn.com/bh.svg" },
    { country: "Bangladesch", img: "https://flagcdn.com/bd.svg" },
    { country: "Barbados", img: "https://flagcdn.com/bb.svg" },
    { country: "Belarus", img: "https://flagcdn.com/by.svg" },
    { country: "Belgien", img: "https://flagcdn.com/be.svg" },
    { country: "Belize", img: "https://flagcdn.com/bz.svg" },
    { country: "Benin", img: "https://flagcdn.com/bj.svg" },
    { country: "Bermuda", img: "https://flagcdn.com/bm.svg" },
    { country: "Bhutan", img: "https://flagcdn.com/bt.svg" },
    { country: "Bolivien", img: "https://flagcdn.com/bo.svg" },
    { country: "Karibisch-Niederlande", img: "https://flagcdn.com/bq.svg" },
    { country: "Bosnien und Herzegowina", img: "https://flagcdn.com/ba.svg" },
    { country: "Botswana", img: "https://flagcdn.com/bw.svg" },
    { country: "Bouvetinsel", img: "https://flagcdn.com/bv.svg" },
    { country: "Brasilien", img: "https://flagcdn.com/br.svg" },
    { country: "Britisches Territorium im Indischen Ozean", img: "https://flagcdn.com/io.svg" },
    { country: "Britische Jungferninseln", img: "https://flagcdn.com/vg.svg" },
    { country: "Brunei", img: "https://flagcdn.com/bn.svg" },
    { country: "Bulgarien", img: "https://flagcdn.com/bg.svg" },
    { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
    { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
    { country: "Kap Verde", img: "https://flagcdn.com/cv.svg" },
    { country: "Kambodscha", img: "https://flagcdn.com/kh.svg" },
    { country: "Kamerun", img: "https://flagcdn.com/cm.svg" },
    { country: "Kanada", img: "https://flagcdn.com/ca.svg" },
    { country: "Kaimaninseln", img: "https://flagcdn.com/ky.svg" },
    { country: "Zentralafrikanische Republik", img: "https://flagcdn.com/cf.svg" },
    { country: "Tschad", img: "https://flagcdn.com/td.svg" },
    { country: "Chile", img: "https://flagcdn.com/cl.svg" },
    { country: "China", img: "https://flagcdn.com/cn.svg" },
    { country: "Weihnachtsinsel", img: "https://flagcdn.com/cx.svg" },
    { country: "Kokosinseln", img: "https://flagcdn.com/cc.svg" },
    { country: "Kolumbien", img: "https://flagcdn.com/co.svg" },
    { country: "Komoren", img: "https://flagcdn.com/km.svg" },
    { country: "Demokratische Republik Kongo", img: "https://flagcdn.com/cd.svg" },
    { country: "Republik Kongo", img: "https://flagcdn.com/cg.svg" },
    { country: "Cookinseln", img: "https://flagcdn.com/ck.svg" },
    { country: "Costa Rica", img: "https://flagcdn.com/cr.svg" },
    { country: "Côte d’Ivoire", img: "https://flagcdn.com/ci.svg" },
    { country: "Kroatien", img: "https://flagcdn.com/hr.svg" },
    { country: "Kuba", img: "https://flagcdn.com/cu.svg" },
    { country: "Curaçao", img: "https://flagcdn.com/cw.svg" },
    { country: "Zypern", img: "https://flagcdn.com/cy.svg" },
    { country: "Tschechien", img: "https://flagcdn.com/cz.svg" },
    { country: "Dänemark", img: "https://flagcdn.com/dk.svg" },
    { country: "Dschibuti", img: "https://flagcdn.com/dj.svg" },
    { country: "Dominica", img: "https://flagcdn.com/dm.svg" },
    { country: "Dominikanische Republik", img: "https://flagcdn.com/do.svg" },
    { country: "Ecuador", img: "https://flagcdn.com/ec.svg" },
    { country: "Ägypten", img: "https://flagcdn.com/eg.svg" },
    { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
    { country: "Äquatorialguinea", img: "https://flagcdn.com/gq.svg" },
    { country: "Eritrea", img: "https://flagcdn.com/er.svg" },
    { country: "Estland", img: "https://flagcdn.com/ee.svg" },
    { country: "Eswatini", img: "https://flagcdn.com/sz.svg" },
    { country: "Äthiopien", img: "https://flagcdn.com/et.svg" },
    { country: "Falklandinseln", img: "https://flagcdn.com/fk.svg" },
    { country: "Färöer", img: "https://flagcdn.com/fo.svg" },
    { country: "Fidschi", img: "https://flagcdn.com/fj.svg" },
    { country: "Finnland", img: "https://flagcdn.com/fi.svg" },
    { country: "Frankreich", img: "https://flagcdn.com/fr.svg" },
    { country: "Französisch-Guayana", img: "https://flagcdn.com/gf.svg" },
    { country: "Französisch-Polynesien", img: "https://flagcdn.com/pf.svg" },
    { country: "Französische Süd- und Antarktisgebiete", img: "https://flagcdn.com/tf.svg" },
    { country: "Gabun", img: "https://flagcdn.com/ga.svg" },
    { country: "Gambia", img: "https://flagcdn.com/gm.svg" },
    { country: "Georgien", img: "https://flagcdn.com/ge.svg" },
    { country: "Deutschland", img: "https://flagcdn.com/de.svg" },
    { country: "Ghana", img: "https://flagcdn.com/gh.svg" },
    { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
    { country: "Griechenland", img: "https://flagcdn.com/gr.svg" },
    { country: "Grönland", img: "https://flagcdn.com/gl.svg" },
    { country: "Grenada", img: "https://flagcdn.com/gd.svg" },
    { country: "Guadeloupe", img: "https://flagcdn.com/gp.svg" },
    { country: "Guam", img: "https://flagcdn.com/gu.svg" },
    { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
    { country: "Guernsey", img: "https://flagcdn.com/gg.svg" },
    { country: "Guinea", img: "https://flagcdn.com/gn.svg" },
    { country: "Guinea-Bissau", img: "https://flagcdn.com/gw.svg" },
    { country: "Guyana", img: "https://flagcdn.com/gy.svg" },
    { country: "Haiti", img: "https://flagcdn.com/ht.svg" },
    { country: "Heard und McDonald-Inseln", img: "https://flagcdn.com/hm.svg" },
    { country: "Vatikanstadt", img: "https://flagcdn.com/va.svg" },
    { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
    { country: "Hongkong", img: "https://flagcdn.com/hk.svg" },
    { country: "Ungarn", img: "https://flagcdn.com/hu.svg" },
    { country: "Island", img: "https://flagcdn.com/is.svg" },
    { country: "Indien", img: "https://flagcdn.com/in.svg" },
    { country: "Indonesien", img: "https://flagcdn.com/id.svg" },
    { country: "Iran", img: "https://flagcdn.com/ir.svg" },
    { country: "Irak", img: "https://flagcdn.com/iq.svg" },
    { country: "Irland", img: "https://flagcdn.com/ie.svg" },
    { country: "Isle of Man", img: "https://flagcdn.com/im.svg" },
    { country: "Israel", img: "https://flagcdn.com/il.svg" },
    { country: "Italien", img: "https://flagcdn.com/it.svg" },
    { country: "Jamaika", img: "https://flagcdn.com/jm.svg" },
    { country: "Japan", img: "https://flagcdn.com/jp.svg" },
    { country: "Jersey", img: "https://flagcdn.com/je.svg" },
    { country: "Jordanien", img: "https://flagcdn.com/jo.svg" },
    { country: "Kasachstan", img: "https://flagcdn.com/kz.svg" },
    { country: "Kenia", img: "https://flagcdn.com/ke.svg" },
    { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
    { country: "Nordkorea", img: "https://flagcdn.com/kp.svg" },
    { country: "Südkorea", img: "https://flagcdn.com/kr.svg" },
    { country: "Kuwait", img: "https://flagcdn.com/kw.svg" },
    { country: "Kirgisistan", img: "https://flagcdn.com/kg.svg" },
    { country: "Laos", img: "https://flagcdn.com/la.svg" },
    { country: "Lettland", img: "https://flagcdn.com/lv.svg" },
    { country: "Libanon", img: "https://flagcdn.com/lb.svg" },
    { country: "Lesotho", img: "https://flagcdn.com/ls.svg" },
    { country: "Liberia", img: "https://flagcdn.com/lr.svg" },
    { country: "Libyen", img: "https://flagcdn.com/ly.svg" },
    { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
    { country: "Litauen", img: "https://flagcdn.com/lt.svg" },
    { country: "Luxemburg", img: "https://flagcdn.com/lu.svg" },
    { country: "Macao", img: "https://flagcdn.com/mo.svg" },
    { country: "Madagaskar", img: "https://flagcdn.com/mg.svg" },
    { country: "Malawi", img: "https://flagcdn.com/mw.svg" },
    { country: "Malaysia", img: "https://flagcdn.com/my.svg" },
    { country: "Malediven", img: "https://flagcdn.com/mv.svg" },
    { country: "Mali", img: "https://flagcdn.com/ml.svg" },
    { country: "Malta", img: "https://flagcdn.com/mt.svg" },
    { country: "Marshallinseln", img: "https://flagcdn.com/mh.svg" },
    { country: "Martinique", img: "https://flagcdn.com/mq.svg" },
    { country: "Mauretanien", img: "https://flagcdn.com/mr.svg" },
    { country: "Mauritius", img: "https://flagcdn.com/mu.svg" },
    { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
    { country: "Mexiko", img: "https://flagcdn.com/mx.svg" },
    { country: "Mikronesien", img: "https://flagcdn.com/fm.svg" },
    { country: "Moldau", img: "https://flagcdn.com/md.svg" },
    { country: "Monaco", img: "https://flagcdn.com/mc.svg" },
    { country: "Mongolei", img: "https://flagcdn.com/mn.svg" },
    { country: "Montenegro", img: "https://flagcdn.com/me.svg" },
    { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
    { country: "Marokko", img: "https://flagcdn.com/ma.svg" },
    { country: "Mosambik", img: "https://flagcdn.com/mz.svg" },
    { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
    { country: "Namibia", img: "https://flagcdn.com/na.svg" },
    { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
    { country: "Nepal", img: "https://flagcdn.com/np.svg" },
    { country: "Niederlande", img: "https://flagcdn.com/nl.svg" },
    { country: "Neukaledonien", img: "https://flagcdn.com/nc.svg" },
    { country: "Neuseeland", img: "https://flagcdn.com/nz.svg" },
    { country: "Nicaragua", img: "https://flagcdn.com/ni.svg" },
    { country: "Niger", img: "https://flagcdn.com/ne.svg" },
    { country: "Nigeria", img: "https://flagcdn.com/ng.svg" },
    { country: "Niue", img: "https://flagcdn.com/nu.svg" },
    { country: "Norfolkinsel", img: "https://flagcdn.com/nf.svg" },
    { country: "Nördliche Marianen", img: "https://flagcdn.com/mp.svg" },
    { country: "Norwegen", img: "https://flagcdn.com/no.svg" },
    { country: "Oman", img: "https://flagcdn.com/om.svg" },
    { country: "Pakistan", img: "https://flagcdn.com/pk.svg" },
    { country: "Palau", img: "https://flagcdn.com/pw.svg" },
    { country: "Palästina", img: "https://flagcdn.com/ps.svg" },
    { country: "Panama", img: "https://flagcdn.com/pa.svg" },
    { country: "Papua-Neuguinea", img: "https://flagcdn.com/pg.svg" },
    { country: "Paraguay", img: "https://flagcdn.com/py.svg" },
    { country: "Peru", img: "https://flagcdn.com/pe.svg" },
    { country: "Philippinen", img: "https://flagcdn.com/ph.svg" },
    { country: "Pitcairninseln", img: "https://flagcdn.com/pn.svg" },
    { country: "Polen", img: "https://flagcdn.com/pl.svg" },
    { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
    { country: "Puerto Rico", img: "https://flagcdn.com/pr.svg" },
    { country: "Katar", img: "https://flagcdn.com/qa.svg" },
    { country: "Réunion", img: "https://flagcdn.com/re.svg" },
    { country: "Rumänien", img: "https://flagcdn.com/ro.svg" },
    { country: "Russland", img: "https://flagcdn.com/ru.svg" },
    { country: "Ruanda", img: "https://flagcdn.com/rw.svg" },
    { country: "Saint-Barthélemy", img: "https://flagcdn.com/bl.svg" },
    { country: "St. Helena", img: "https://flagcdn.com/sh.svg" },
    { country: "St. Kitts und Nevis", img: "https://flagcdn.com/kn.svg" },
    { country: "St. Lucia", img: "https://flagcdn.com/lc.svg" },
    { country: "Saint-Martin", img: "https://flagcdn.com/mf.svg" },
    { country: "St. Pierre und Miquelon", img: "https://flagcdn.com/pm.svg" },
    { country: "St. Vincent und die Grenadinen", img: "https://flagcdn.com/vc.svg" },
    { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
    { country: "San Marino", img: "https://flagcdn.com/sm.svg" },
    { country: "São Tomé und Príncipe", img: "https://flagcdn.com/st.svg" },
    { country: "Saudi-Arabien", img: "https://flagcdn.com/sa.svg" },
    { country: "Senegal", img: "https://flagcdn.com/sn.svg" },
    { country: "Serbien", img: "https://flagcdn.com/rs.svg" },
    { country: "Seychellen", img: "https://flagcdn.com/sc.svg" },
    { country: "Sierra Leone", img: "https://flagcdn.com/sl.svg" },
    { country: "Singapur", img: "https://flagcdn.com/sg.svg" },
    { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
    { country: "Slowakei", img: "https://flagcdn.com/sk.svg" },
    { country: "Slowenien", img: "https://flagcdn.com/si.svg" },
    { country: "Salomon-Inseln", img: "https://flagcdn.com/sb.svg" },
    { country: "Somalia", img: "https://flagcdn.com/so.svg" },
    { country: "Südafrika", img: "https://flagcdn.com/za.svg" },
    { country: "Südgeorgien und die Südlichen Sandwichinseln", img: "https://flagcdn.com/gs.svg" },
    { country: "Südsudan", img: "https://flagcdn.com/ss.svg" },
    { country: "Spanien", img: "https://flagcdn.com/es.svg" },
    { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
    { country: "Sudan", img: "https://flagcdn.com/sd.svg" },
    { country: "Suriname", img: "https://flagcdn.com/sr.svg" },
    { country: "Svalbard und Jan Mayen", img: "https://flagcdn.com/sj.svg" },
    { country: "Schweden", img: "https://flagcdn.com/se.svg" },
    { country: "Schweiz", img: "https://flagcdn.com/ch.svg" },
    { country: "Syrien", img: "https://flagcdn.com/sy.svg" },
    { country: "Taiwan", img: "https://flagcdn.com/tw.svg" },
    { country: "Tadschikistan", img: "https://flagcdn.com/tj.svg" },
    { country: "Tansania", img: "https://flagcdn.com/tz.svg" },
    { country: "Thailand", img: "https://flagcdn.com/th.svg" },
    { country: "Timor-Leste", img: "https://flagcdn.com/tl.svg" },
    { country: "Togo", img: "https://flagcdn.com/tg.svg" },
    { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
    { country: "Tonga", img: "https://flagcdn.com/to.svg" },
    { country: "Trinidad und Tobago", img: "https://flagcdn.com/tt.svg" },
    { country: "Tunesien", img: "https://flagcdn.com/tn.svg" },
    { country: "Türkei", img: "https://flagcdn.com/tr.svg" },
    { country: "Turkmenistan", img: "https://flagcdn.com/tm.svg" },
    { country: "Turks- und Caicosinseln", img: "https://flagcdn.com/tc.svg" },
    { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
    { country: "Uganda", img: "https://flagcdn.com/ug.svg" },
    { country: "Ukraine", img: "https://flagcdn.com/ua.svg" },
    { country: "Vereinigte Arabische Emirate", img: "https://flagcdn.com/ae.svg" },
    { country: "Vereinigtes Königreich", img: "https://flagcdn.com/gb.svg" },
    { country: "Vereinigte Staaten", img: "https://flagcdn.com/us.svg" },
    { country: "Kleinere Außengebiete der USA", img: "https://flagcdn.com/um.svg" },
    { country: "Uruguay", img: "https://flagcdn.com/uy.svg" },
    { country: "Usbekistan", img: "https://flagcdn.com/uz.svg" },
    { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
    { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
    { country: "Vietnam", img: "https://flagcdn.com/vn.svg" },
    { country: "Wallis und Futuna", img: "https://flagcdn.com/wf.svg" },
    { country: "Westsahara", img: "https://flagcdn.com/eh.svg" },
    { country: "Jemen", img: "https://flagcdn.com/ye.svg" },
    { country: "Sambia", img: "https://flagcdn.com/zm.svg" },
    { country: "Simbabwe", img: "https://flagcdn.com/zw.svg" },
    { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
