window.RECIPES_DB = [
	{ name: "Kimchi-Jjigae", ingredients: ["Kimchi", "Schweinefleisch", "Tofu", "Zwiebel", "Frühlingszwiebel", "Knoblauch", "Chilipulver", "Gochujang", "Sojasauce"] },
	{ name: "Bibimbap", ingredients: ["Reis", "Rindfleisch", "Spinat", "Bohnensprossen", "Karotte", "Zucchini", "Ei", "Gochujang", "Algen"] },
	{ name: "Bulgogi", ingredients: ["Rindfleisch", "Sojasauce", "Zwiebel", "Birne", "Zucker", "Sesamöl", "Knoblauch", "Frühlingszwiebel", "Pfeffer"] },
	{ name: "Japchae", ingredients: ["Glasnudeln", "Rindfleisch", "Spinat", "Karotte", "Zwiebel", "Pilze", "Ei", "Sojasauce", "Sesamöl"] },
	{ name: "Tteokbokki", ingredients: ["Reiskuchen", "Fischkuchen", "Zwiebel", "Frühlingszwiebel", "Gochujang", "Zucker", "Sojasauce", "Knoblauch", "gekochtes Ei"] },
	{ name: "Sundubu-Jjigae", ingredients: ["Seidentofu", "Schweinefleisch", "Ei", "Zucchini", "Zwiebel", "Frühlingszwiebel", "Knoblauch", "Chilipulver", "Sojasauce"] },
	{ name: "Samgyeopsal", ingredients: ["Schweinebauch", "Salat", "Knoblauch", "Ssamjang", "Frühlingszwiebel", "Salz", "Pfeffer"] },
	{ name: "Kimchi-Bokkeumbap", ingredients: ["Kimchi", "Reis", "Ei", "Schweinefleisch", "Frühlingszwiebel", "Sojasauce", "Sesamöl"] },
	{ name: "Galbijjim", ingredients: ["Rinderrippen", "Zwiebel", "Karotte", "Kartoffel", "Sojasauce", "Zucker", "Birne", "Knoblauch", "Sesamöl"] },
	{ name: "Jjajangmyeon", ingredients: ["Nudeln", "Schweinefleisch", "Zwiebel", "Zucchini", "Kartoffel", "Chunjang", "Gurke", "Ei"] },
	{ name: "Sushi", ingredients: ["Reis", "Essig", "Zucker", "Salz", "Algen", "Lachs", "Thunfisch", "Garnele", "Avocado", "Gurke"] },
	{ name: "Ramen", ingredients: ["Nudeln", "Schweinefleisch", "Ei", "Frühlingszwiebel", "Menma", "Algen", "Sojasauce", "Miso", "Knoblauch"] },
	{ name: "Katsudon", ingredients: ["Reis", "Tonkatsu", "Ei", "Zwiebel", "Sojasauce", "Zucker", "Mirin"] },
	{ name: "Okonomiyaki", ingredients: ["Weizenmehl", "Ei", "Kohl", "Schweinefleisch", "Garnele", "Frühlingszwiebel", "Mayonnaise", "Okonomiyaki-Sauce"] },
	{ name: "Mapo Tofu", ingredients: ["Tofu", "Hackfleisch vom Schwein", "Frühlingszwiebel", "Knoblauch", "Ingwer", "Sojasauce", "Doubanjiang", "Sichuanpfeffer"] },
	{ name: "Peking-Ente", ingredients: ["Ente", "Gurke", "Frühlingszwiebel", "Hoisin-Sauce", "Pfannkuchen"] },
	{ name: "Süß-Sauer-Schweinefleisch", ingredients: ["Schweinefleisch", "Ananas", "Paprika", "Zwiebel", "Essig", "Zucker", "Ketchup", "Sojasauce"] },
	{ name: "Pad Thai", ingredients: ["Reisnudeln", "Garnele", "Ei", "Tofu", "Bohnensprossen", "Erdnüsse", "Tamarinde", "Fischsauce", "Limette"] },
	{ name: "Tom Yum Kung", ingredients: ["Garnele", "Zitronengras", "Limette", "Galangal", "Pilze", "Chili", "Fischsauce", "Koriander"] },
	{ name: "Pho", ingredients: ["Reisnudeln", "Rindfleisch", "Zwiebel", "Ingwer", "Zimt", "Nelken", "Fischsauce", "Bohnensprossen", "Limette", "Basilikum"] },
	{ name: "Hainanese Hühnchenreis", ingredients: ["Hühnchen", "Reis", "Ingwer", "Knoblauch", "Gurke", "Sojasauce", "Chilisauce"] },
	{ name: "Sommerrollen", ingredients: ["Reispapier", "Garnele", "Schweinefleisch", "Salat", "Reisnudeln", "Minze", "Koriander"] },
	{ name: "Grünes Curry", ingredients: ["Hühnchen", "grüne Currypaste", "Kokosmilch", "Aubergine", "Basilikum", "Fischsauce", "Zucker"] },
	{ name: "Nasi Goreng", ingredients: ["Reis", "Hühnchen", "Ei", "Sojasauce", "Garnele", "Frühlingszwiebel", "Chili"] },
	{ name: "Satay", ingredients: ["Hühnchen", "Erdnüsse", "Sojasauce", "Zitronengras", "Knoblauch", "Kurkuma"] },
	{ name: "Laksa", ingredients: ["Reisnudeln", "Garnele", "Kokosmilch", "Tofu", "Bohnensprossen", "Ei", "Chili", "Koriander"] },
	{ name: "Chow Mein", ingredients: ["Nudeln", "Hühnchen", "Bohnensprossen", "Kohl", "Karotte", "Sojasauce", "Frühlingszwiebel"] },
	{ name: "Gebratener Reis", ingredients: ["Reis", "Ei", "Karotte", "Erbsen", "Frühlingszwiebel", "Garnele", "Sojasauce"] },
	{ name: "Gyoza", ingredients: ["Weizenmehl", "Kohl", "Schweinefleisch", "Knoblauch", "Ingwer", "Frühlingszwiebel", "Sojasauce"] },
	{ name: "Unadon", ingredients: ["Reis", "Aal", "Sojasauce", "Mirin", "Zucker", "Ei"] },
	{ name: "Hamburger", ingredients: ["Rindfleisch", "Brötchen", "Salat", "Tomate", "Zwiebel", "Käse", "Essiggurke"] },
	{ name: "Cheeseburger", ingredients: ["Rindfleisch", "Brötchen", "Käse", "Salat", "Tomate", "Zwiebel", "Essiggurke"] },
	{ name: "Fried Chicken", ingredients: ["Hühnchen", "Weizenmehl", "Ei", "Speiseöl", "Salz", "Pfeffer"] },
	{ name: "BBQ-Spareribs", ingredients: ["Schweinerippchen", "BBQ-Sauce", "brauner Zucker", "Salz", "Pfeffer", "Knoblauchpulver"] },
	{ name: "Caesar-Salat", ingredients: ["Salat", "Parmesan", "Croutons", "Sardellen", "Ei", "Caesar-Dressing"] },
	{ name: "BLT-Sandwich", ingredients: ["Brot", "Speck", "Salat", "Tomate", "Mayonnaise"] },
	{ name: "Spaghetti Carbonara", ingredients: ["Spaghetti", "Ei", "Parmesan", "Pancetta", "Pfeffer"] },
	{ name: "Lasagne", ingredients: ["Lasagneplatten", "Hackfleisch vom Rind", "Tomatensauce", "Ricotta", "Mozzarella", "Parmesan", "Ei"] },
	{ name: "Pizza Margherita", ingredients: ["Pizzateig", "Tomatensauce", "Mozzarella", "Basilikum", "Olivenöl"] },
	{ name: "Paella", ingredients: ["Reis", "Garnele", "Miesmuscheln", "Hühnchen", "Chorizo", "Erbsen", "Safran", "Paprika", "Paprika"] },
	{ name: "Croque Monsieur", ingredients: ["Brot", "Schinken", "Käse", "Butter", "Milch", "Weizenmehl", "Senf"] },
	{ name: "Quiche Lorraine", ingredients: ["Quicheteig", "Ei", "Speck", "Käse", "Sahne", "Zwiebel"] },
	{ name: "Ratatouille", ingredients: ["Aubergine", "Zucchini", "Paprika", "Tomate", "Zwiebel", "Knoblauch"] },
	{ name: "Bouillabaisse", ingredients: ["Fisch", "Miesmuscheln", "Garnele", "Tomate", "Knoblauch", "Zwiebel", "Fenchel", "Safran"] },
	{ name: "Crêpe", ingredients: ["Weizenmehl", "Ei", "Milch", "Butter", "Zucker", "Salz"] },
	{ name: "Spanisches Omelett", ingredients: ["Ei", "Kartoffel", "Zwiebel", "Olivenöl", "Salz"] },
	{ name: "Gazpacho", ingredients: ["Tomate", "Gurke", "Paprika", "Zwiebel", "Knoblauch", "Olivenöl", "Essig"] },
	{ name: "Patatas Bravas", ingredients: ["Kartoffel", "Olivenöl", "Paprika", "Tomate", "Aioli-Sauce"] },
	{ name: "Churros", ingredients: ["Weizenmehl", "Ei", "Butter", "Zucker", "Salz", "Speiseöl", "Zimt"] },
	{ name: "Salade Niçoise", ingredients: ["Salat", "Thunfisch", "Ei", "Kartoffel", "grüne Bohnen", "Oliven", "Tomate", "Sardellen"] },
	{ name: "Tacos", ingredients: ["Tortilla", "Rindfleisch", "Salat", "Tomate", "Käse", "Zwiebel", "Sauerrahm", "Guacamole"] },
	{ name: "Enchilada", ingredients: ["Tortilla", "Hühnchen", "Käse", "Zwiebel", "Enchilada-Sauce", "Sauerrahm"] },
	{ name: "Burrito", ingredients: ["Tortilla", "Reis", "Bohnen", "Rindfleisch", "Salat", "Käse", "Salsa"] },
	{ name: "Ceviche", ingredients: ["Fisch", "Limette", "Zwiebel", "Chili", "Koriander", "Tomate"] },
	{ name: "Feijoada", ingredients: ["schwarze Bohnen", "Schweinefleisch", "Rindfleisch", "Wurst", "Reis", "Zwiebel", "Knoblauch"] },
	{ name: "Empanada", ingredients: ["Weizenmehl", "Rindfleisch", "Zwiebel", "Ei", "Oliven", "Rosinen", "Paprika"] },
	{ name: "Moussaka", ingredients: ["Aubergine", "Kartoffel", "Hackfleisch vom Rind", "Tomate", "Zwiebel", "Béchamelsauce"] },
	{ name: "Griechischer Salat", ingredients: ["Tomate", "Gurke", "Oliven", "Feta-Käse", "Zwiebel", "Olivenöl"] },
	{ name: "Shakshuka", ingredients: ["Ei", "Tomate", "Paprika", "Zwiebel", "Knoblauch", "Kreuzkümmel", "Paprika"] },
	{ name: "Falafel", ingredients: ["Kichererbsen", "Zwiebel", "Knoblauch", "Petersilie", "Koriander", "Kreuzkümmel", "Weizenmehl"] },
	{ name: "Hummus", ingredients: ["Kichererbsen", "Tahini", "Knoblauch", "Zitrone", "Olivenöl"] },
	{ name: "Shawarma", ingredients: ["Hühnchen", "Rindfleisch", "Pita-Brot", "Salat", "Tomate", "Zwiebel", "Joghurt", "Knoblauch"] },
	{ name: "Couscous", ingredients: ["Couscous", "Hühnchen", "Karotte", "Zucchini", "Kichererbsen", "Zwiebel"] },
	{ name: "Tajine", ingredients: ["Lammfleisch", "Aprikosen", "Mandeln", "Zwiebel", "Zimt", "Koriander", "Safran"] },
	{ name: "Butter Chicken", ingredients: ["Hühnchen", "Butter", "Sahne", "Tomate", "Zwiebel", "Garam Masala"] },
	{ name: "Tandoori Chicken", ingredients: ["Hühnchen", "Joghurt", "Garam Masala", "Kreuzkümmel", "Knoblauch", "Ingwer", "Chili"] },
	{ name: "Palak Paneer", ingredients: ["Spinat", "Paneer", "Sahne", "Zwiebel", "Tomate", "Knoblauch", "Kreuzkümmel"] },
	{ name: "Dal Tadka", ingredients: ["Linsen", "Zwiebel", "Tomate", "Knoblauch", "Ingwer", "Kreuzkümmel", "Kurkuma", "Ghee-Butter"] },
	{ name: "Biryani", ingredients: ["Reis", "Hühnchen", "Joghurt", "Zwiebel", "Garam Masala", "Safran"] },
	{ name: "Samosa", ingredients: ["Weizenmehl", "Kartoffel", "Erbsen", "Zwiebel", "Kreuzkümmel", "Koriander"] },
	{ name: "Fettuccine Alfredo", ingredients: ["Fettuccine", "Butter", "Sahne", "Parmesan"] },
	{ name: "Chicken Parmigiana", ingredients: ["Hühnchen", "Ei", "Paniermehl", "Parmesan", "Mozzarella", "Tomatensauce"] },
	{ name: "Boeuf Stroganoff", ingredients: ["Rindfleisch", "Zwiebel", "Pilze", "Sauerrahm", "Butter", "Weizenmehl"] },
	{ name: "Eggs Benedict", ingredients: ["Ei", "English Muffin", "Schinken", "Hollandaise-Sauce", "Butter"] },
	{ name: "Hummerbisque", ingredients: ["Hummer", "Sahne", "Butter", "Zwiebel", "Sellerie", "Karotte", "Cognac"] },
	{ name: "Clam Chowder", ingredients: ["Muscheln", "Kartoffel", "Zwiebel", "Sellerie", "Speck", "Sahne", "Butter"] },
	{ name: "Hühnchen-Pot Pie", ingredients: ["Hühnchen", "Karotte", "Kartoffel", "Erbsen", "Zwiebel", "Teig", "Sahne"] },
	{ name: "Hackbraten", ingredients: ["Rindfleisch", "Ei", "Paniermehl", "Zwiebel", "Ketchup", "Senf"] },
	{ name: "French Toast", ingredients: ["Brot", "Ei", "Milch", "Zimt", "Zucker", "Butter"] },
	{ name: "Pfannkuchen", ingredients: ["Weizenmehl", "Ei", "Milch", "Backpulver", "Zucker", "Butter"] },
	{ name: "Waffeln", ingredients: ["Weizenmehl", "Ei", "Milch", "Backpulver", "Zucker", "Butter"] },
	{ name: "Bananenbrot", ingredients: ["Banane", "Weizenmehl", "Ei", "Zucker", "Butter"] },
	{ name: "Apfelkuchen", ingredients: ["Apfel", "Weizenmehl", "Ei", "Zucker", "Butter", "Zimt"] },
	{ name: "Zitronentarte", ingredients: ["Zitrone", "Ei", "Zucker", "Butter", "Weizenmehl"] },
	{ name: "Brownie", ingredients: ["Schokolade", "Weizenmehl", "Ei", "Zucker", "Butter"] },
	{ name: "Käsekuchen", ingredients: ["Frischkäse", "Ei", "Zucker", "Butter", "Graham Cracker"] },
	{ name: "Kürbissuppe", ingredients: ["Kürbis", "Zwiebel", "Knoblauch", "Sahne", "Butter"] },
	{ name: "Minestrone", ingredients: ["Bohnen", "Karotte", "Sellerie", "Zwiebel", "Tomate", "Nudeln"] },
	{ name: "Omelett", ingredients: ["Ei", "Milch", "Käse", "Schinken", "Zwiebel", "Paprika"] },
	{ name: "Rührei", ingredients: ["Ei", "Milch", "Butter", "Salz", "Pfeffer"] },
	{ name: "Quesadilla", ingredients: ["Tortilla", "Käse", "Hühnchen", "Paprika", "Zwiebel"] },
	{ name: "Fajita", ingredients: ["Rindfleisch", "Zwiebel", "Paprika", "Tortilla", "Sauerrahm"] },
	{ name: "Pulled Pork", ingredients: ["Schweinefleisch", "BBQ-Sauce", "brauner Zucker", "Zwiebel", "Brot"] },
	{ name: "Fish and Chips", ingredients: ["Fisch", "Kartoffel", "Weizenmehl", "Ei", "Speiseöl"] },
	{ name: "Shepherd's Pie", ingredients: ["Hackfleisch vom Lamm", "Kartoffel", "Karotte", "Zwiebel", "Erbsen", "Bratensauce"] },
	{ name: "Steak", ingredients: ["Rindfleisch", "Salz", "Pfeffer", "Butter", "Knoblauch"] },
	{ name: "Lammkotelett", ingredients: ["Lammfleisch", "Salz", "Pfeffer", "Knoblauch", "Rosmarin"] },
	{ name: "Gebratenes Hühnchen", ingredients: ["Hühnchen", "Salz", "Pfeffer", "Knoblauch", "Thymian", "Olivenöl"] },
	{ name: "Hühnercurry", ingredients: ["Hühnchen", "Zwiebel", "Tomate", "Knoblauch", "Ingwer", "Currypulver", "Kokosmilch"] },
	{ name: "Shrimp Scampi", ingredients: ["Garnele", "Knoblauch", "Butter", "Zitrone", "Petersilie", "Spaghetti"] },
	{ name: "Meeresfrüchte-Paella", ingredients: ["Reis", "Garnele", "Miesmuscheln", "Tintenfisch", "Erbsen", "Safran"] },
	{ name: "Cacciatore", ingredients: ["Hühnchen", "Tomate", "Zwiebel", "Paprika", "Pilze", "Knoblauch"] },
	{ name: "Boeuf Daube", ingredients: ["Rindfleisch", "Rotwein", "Zwiebel", "Karotte", "Sellerie", "Knoblauch", "Thymian"] },
	{ name: "Gulasch", ingredients: ["Rindfleisch", "Zwiebel", "Paprika", "Tomate", "Paprika", "Knoblauch"] },
	{ name: "Borschtsch", ingredients: ["Rote Bete", "Kohl", "Kartoffel", "Karotte", "Zwiebel", "Dill"] },
	{ name: "Pierogi", ingredients: ["Weizenmehl", "Ei", "Kartoffel", "Käse", "Zwiebel", "Butter"] },
	{ name: "Baklava", ingredients: ["Filoteig", "Walnüsse", "Pistazien", "Zucker", "Butter", "Honig"] },
	{ name: "Dolma", ingredients: ["Weinblätter", "Reis", "Zwiebel", "Pinienkerne", "Dill"] },
	{ name: "Kohlrouladen", ingredients: ["Kohl", "Hackfleisch vom Rind", "Reis", "Zwiebel", "Tomatensauce"] },
	{ name: "Irish Stew", ingredients: ["Lammfleisch", "Kartoffel", "Karotte", "Zwiebel", "Sellerie"] },
	{ name: "Cassoulet", ingredients: ["weiße Bohnen", "Schweinefleisch", "Ente", "Wurst", "Zwiebel", "Knoblauch"] },
	{ name: "Börek", ingredients: ["Filoteig", "Käse", "Kartoffel", "Ei", "Sesam"] },
	{ name: "Sauerbraten", ingredients: ["Rindfleisch", "Zwiebel", "Karotte", "Sellerie", "Essig", "Ingwer"] },
	{ name: "Wiener Schnitzel", ingredients: ["Kalb", "Ei", "Weizenmehl", "Paniermehl", "Zitrone"] },
	{ name: "Zwiebelrostbraten", ingredients: ["Rindfleisch", "Zwiebel", "Butter", "Weizenmehl", "Rinderbrühe"] },
	{ name: "Rösti", ingredients: ["Kartoffel", "Butter", "Zwiebel", "Speck"] },
	{ name: "Spätzle", ingredients: ["Weizenmehl", "Ei", "Milch", "Butter"] },
	{ name: "Gulaschsuppe", ingredients: ["Rindfleisch", "Zwiebel", "Paprika", "Kartoffel", "Karotte"] },
	{ name: "Chicken Kiew", ingredients: ["Hühnchen", "Butter", "Knoblauch", "Petersilie", "Ei", "Weizenmehl", "Paniermehl"] },
	{ name: "Plov", ingredients: ["Reis", "Rindfleisch", "Karotte", "Zwiebel", "Kreuzkümmel"] },
	{ name: "Manti", ingredients: ["Weizenmehl", "Ei", "Rindfleisch", "Zwiebel", "Joghurt"] },
	{ name: "Peking-Nudeln", ingredients: ["Nudeln", "Schweinefleisch", "Ei", "Frühlingszwiebel", "Sojasauce"] },
	{ name: "Jollof-Reis", ingredients: ["Reis", "Tomate", "Zwiebel", "Paprika", "Chili", "Knoblauch"] },
	{ name: "Bobotie", ingredients: ["Rindfleisch", "Brot", "Ei", "Zwiebel", "Milch", "Currypulver"] },
	{ name: "Bunny Chow", ingredients: ["Brot", "Hühnchen", "Zwiebel", "Tomate", "Currypulver"] },
	{ name: "Chakalaka", ingredients: ["Bohnen", "Zwiebel", "Tomate", "Chili", "Karotte", "Paprika"] },
	{ name: "Pav Bhaji", ingredients: ["Brot", "Kartoffel", "Erbsen", "Karotte", "Zwiebel", "Tomate", "Butter"] },
	{ name: "Vada Pav", ingredients: ["Brot", "Kartoffel", "Chili", "Koriander", "Knoblauch", "Senfsamen"] },
	{ name: "Masala Dosa", ingredients: ["Reis", "Linsen", "Kartoffel", "Zwiebel", "Senfsamen", "Curryblätter"] },
	{ name: "Idli", ingredients: ["Reis", "Linsen", "Salz"] },
	{ name: "Sambar", ingredients: ["Linsen", "Karotte", "Zwiebel", "Tomate", "Aubergine", "Drumsticks", "Gewürzmischung"] },
	{ name: "Katsu Curry", ingredients: ["Reis", "Tonkatsu", "Currysauce", "Zwiebel", "Karotte", "Kartoffel"] },
	{ name: "Takoyaki", ingredients: ["Weizenmehl", "Ei", "Oktopus", "Frühlingszwiebel", "Tempura-Stücke", "Mayonnaise", "Takoyaki-Sauce"] },
	{ name: "Sukiyaki", ingredients: ["Rindfleisch", "Tofu", "Frühlingszwiebel", "Shiitake-Pilze", "Glasnudeln", "Ei"] },
	{ name: "Nabe", ingredients: ["Kohl", "Tofu", "Shiitake-Pilze", "Karotte", "Hühnchen", "Udon"] },
	{ name: "Eiersuppe", ingredients: ["Ei", "Hühnerbrühe", "Kartoffelstärke", "Frühlingszwiebel", "Sojasauce"] },
	{ name: "Sauer-Scharf-Suppe", ingredients: ["Tofu", "Ei", "Pilze", "Bambussprossen", "Essig", "Sojasauce", "Pfeffer"] },
	{ name: "Rindfleisch mit Brokkoli", ingredients: ["Rindfleisch", "Brokkoli", "Sojasauce", "Knoblauch", "Ingwer", "Zwiebel"] },
	{ name: "Zitronenhähnchen", ingredients: ["Hühnchen", "Zitrone", "Ei", "Weizenmehl", "Sojasauce", "Zucker"] },
	{ name: "Ananas-Reis", ingredients: ["Reis", "Ananas", "Garnele", "Ei", "Cashewnüsse", "Frühlingszwiebel"] },
	{ name: "Banh Mi", ingredients: ["Baguette", "Schweinefleisch", "Karotte", "Gurke", "Koriander", "Mayonnaise", "Pastete"] },
	{ name: "Khao Soi", ingredients: ["Eiernudeln", "Hühnchen", "Kokosmilch", "Currypaste", "eingelegtes Gemüse"] },
	{ name: "Bak Kut Teh", ingredients: ["Schweinerippchen", "Knoblauch", "Sojasauce", "weißer Pfeffer", "Pilze"] },
	{ name: "Singapur Laksa", ingredients: ["Reisnudeln", "Garnele", "Kokosmilch", "Tofu", "Bohnensprossen", "Ei", "Chili", "Koriander"] },
	{ name: "Gado-Gado", ingredients: ["Gemüse", "Tofu", "Ei", "Erdnusssauce", "Bohnensprossen"] },
	{ name: "Nasi Lemak", ingredients: ["Reis", "Kokosmilch", "Ei", "Sardellen", "Erdnüsse", "Gurke", "Sambalsauce"] },
	{ name: "Rucola-Pesto-Pasta", ingredients: ["Rucola", "Nudeln", "Parmesan", "Olivenöl", "Pinienkerne"] },
	{ name: "Feta-Shakshuka", ingredients: ["Ei", "Tomate", "Paprika", "Zwiebel", "Feta-Käse", "Koriander"] },
	{ name: "Buttermilchpfannkuchen", ingredients: ["Weizenmehl", "Ei", "Buttermilch", "Zucker", "Backpulver"] },
	{ name: "Quinoa-Salat", ingredients: ["Quinoa", "Gurke", "Tomate", "Feta-Käse", "Zitrone", "Olivenöl"] },
	{ name: "Grünkohl-Caesar-Salat", ingredients: ["Grünkohl", "Parmesan", "Croutons", "Sardellen", "Ei", "Caesar-Dressing"] },
	{ name: "Vegan Buddha Bowl", ingredients: ["brauner Reis", "Kichererbsen", "Avocado", "Spinat", "Karotte", "Tofu"] },
	{ name: "Aubergine Parmigiana", ingredients: ["Aubergine", "Tomatensauce", "Mozzarella", "Parmesan", "Basilikum"] },
	{ name: "Gefüllte Paprika", ingredients: ["Paprika", "Reis", "Hackfleisch vom Rind", "Zwiebel", "Tomate", "Käse"] },
	{ name: "Gebratene Lammkoteletts", ingredients: ["Lammfleisch", "Knoblauch", "Rosmarin", "Olivenöl", "Salz", "Pfeffer"] },
	{ name: "Linsensuppe", ingredients: ["Linsen", "Karotte", "Sellerie", "Zwiebel", "Tomate", "Knoblauch"] },
	{ name: "Gebratener Rosenkohl", ingredients: ["Rosenkohl", "Olivenöl", "Salz", "Pfeffer", "Zitrone"] },
	{ name: "Pesto-Hühnchen", ingredients: ["Hühnchen", "Basilikumpesto", "Parmesan", "Olivenöl"] },
	{ name: "Mango-Salsa", ingredients: ["Mango", "Zwiebel", "Limette", "Koriander", "Chili"] },
	{ name: "Gebratener Kabeljau", ingredients: ["Kabeljau", "Zitrone", "Olivenöl", "Petersilie", "Paniermehl"] },
	{ name: "Asiatischer Krautsalat", ingredients: ["Chinaball", "Karotte", "Frühlingszwiebel", "Sojasauce", "Reisessig", "Sesamöl"] },
	{ name: "Erdnussnudelsalat", ingredients: ["Nudeln", "Erdnüsse", "Karotte", "Gurke", "Sojasauce", "Sesamöl"] },
	{ name: "Vegan Chili", ingredients: ["schwarze Bohnen", "Tomate", "Zwiebel", "Chilipulver", "Mais", "Paprika"] },
	{ name: "Jackfrucht-Tacos", ingredients: ["Jackfrucht", "Tortilla", "Kohl", "Limette", "Avocado", "Koriander"] },
	{ name: "Tofu-Gemüse-Pfanne", ingredients: ["Tofu", "Brokkoli", "Paprika", "Sojasauce", "Ingwer", "Knoblauch"] },
	{ name: "Kürbisrisotto", ingredients: ["Kürbis", "Reis", "Parmesan", "Zwiebel", "Knoblauch"] },
	{ name: "Ratatouille-Toast", ingredients: ["Aubergine", "Zucchini", "Paprika", "Zwiebel", "Brot"] },
	{ name: "Rote-Bete-Salat", ingredients: ["Rote Bete", "Rucola", "Walnüsse", "Ziegenkäse", "Balsamico"] },
	{ name: "Marokkanische Tajine", ingredients: ["Lammfleisch", "Aprikosen", "Mandeln", "Zwiebel", "Zimt", "Koriander", "Safran"] },
	{ name: "Chimichurri-Steak", ingredients: ["Rindfleisch", "Petersilie", "Knoblauch", "Olivenöl", "Oregano", "Essig"] },
	{ name: "Zucchini-Puffer", ingredients: ["Zucchini", "Ei", "Weizenmehl", "Parmesan", "Frühlingszwiebel"] },
	{ name: "Miso-Suppe", ingredients: ["Miso", "Tofu", "Algen", "Frühlingszwiebel", "Dashi-Brühe"] },
	{ name: "Falafel-Wrap", ingredients: ["Falafel", "Pita-Brot", "Salat", "Tomate", "Tahini"] },
	{ name: "Garnelen-Laksa", ingredients: ["Garnele", "Reisnudeln", "Kokosmilch", "Laksa-Paste", "Ei", "Bohnensprossen"] },
	{ name: "Couscous-Bowl", ingredients: ["Couscous", "Kichererbsen", "Karotte", "Zucchini", "Zitrone"] },
	{ name: "Dakgangjeong", ingredients: ["Hühnchen", "Gochujang", "Sojasauce", "Zucker", "Reissirup", "Knoblauch", "Ingwer", "Backpulver"] },
	{ name: "Budae-Jjigae", ingredients: ["Schinken", "Wurst", "Kimchi", "Tofu", "Bohnensprossen", "Ramen", "Gochujang", "Chilipulver", "Frühlingszwiebel"] },
	{ name: "Galbitang", ingredients: ["Rinderrippen", "Rettich", "Frühlingszwiebel", "Knoblauch", "Ingwer", "Sojasauce", "Glasnudeln"] },
	{ name: "Meeresfrüchte-Pajeon", ingredients: ["Tintenfisch", "Garnele", "Schnittlauch", "Weizenmehl", "Ei", "Wasser", "Sojasauce", "Essig"] },
	{ name: "Yukgaejang", ingredients: ["Rindfleisch", "Farn", "Bohnensprossen", "Taro-Stiele", "Frühlingszwiebel", "Chilipulver", "Sojasauce", "Knoblauch"] },
	{ name: "Bossam", ingredients: ["Schweinefleisch", "Knoblauch", "Ingwer", "Frühlingszwiebel", "Miso", "gesalzene Garnelen", "Rettich-Kimchi", "Chinaball"] },
	{ name: "Samgyetang", ingredients: ["Hühnchen", "Ginseng", "Jujube", "Knoblauch", "Klebreis", "Frühlingszwiebel", "Salz"] },
	{ name: "Jjimdak", ingredients: ["Hühnchen", "Kartoffel", "Karotte", "Zwiebel", "Frühlingszwiebel", "Glasnudeln", "Sojasauce", "Zucker", "Knoblauch"] },
	{ name: "Bibim-Guksu", ingredients: ["Nudeln", "Gochujang", "Essig", "Zucker", "Gurke", "Salat", "Ei", "Sesamöl"] },
	{ name: "Gimbap", ingredients: ["Reis", "Algen", "eingelegter Rettich", "Spinat", "Karotte", "Ei", "Schinken", "Fischkuchen", "Sesamöl"] },
	{ name: "Jeyuk-Bokkeum", ingredients: ["Schweinefleisch", "Gochujang", "Chilipulver", "Sojasauce", "Zucker", "Knoblauch", "Zwiebel", "Frühlingszwiebel"] },
	{ name: "Dakbokkeumtang", ingredients: ["Hühnchen", "Kartoffel", "Karotte", "Zwiebel", "Frühlingszwiebel", "Gochujang", "Chilipulver", "Knoblauch"] },
	{ name: "Doenjang-Jjigae", ingredients: ["Miso", "Tofu", "Zucchini", "Zwiebel", "Frühlingszwiebel", "Pilze", "Chili", "Sardellenbrühe"] },
	{ name: "Agujjim", ingredients: ["Seeteufel", "Bohnensprossen", "Seeananas", "Wasserkresse", "Chilipulver", "Knoblauch", "Sojasauce", "Kartoffelstärke"] },
	{ name: "Gopchang-Jeongol", ingredients: ["Rinderdarm", "Frühlingszwiebel", "Zwiebel", "Sesamblätter", "Pilze", "Tofu", "Chilipulver", "gehackter Knoblauch", "Brühe"] },
	{ name: "Yangnyeom-Chicken", ingredients: ["Hühnchen", "Gochujang", "Reissirup", "Ketchup", "Knoblauch", "Sojasauce", "Erdnüsse", "Backpulver"] },
	{ name: "Gukbap", ingredients: ["Reis", "Schweinefleisch", "Innereien", "Frühlingszwiebel", "Knoblauch", "Chilipulver", "Sundae"] },
	{ name: "Pasta Aglio e Olio", ingredients: ["Spaghetti", "Knoblauch", "Olivenöl", "Peperoncino", "Petersilie"] },
	{ name: "Vongole Pasta", ingredients: ["Spaghetti", "Venusmuscheln", "Knoblauch", "Olivenöl", "Weißwein", "Petersilie"] },
	{ name: "Gambas al Ajillo", ingredients: ["Garnele", "Knoblauch", "Olivenöl", "Peperoncino", "Baguette"] },
	{ name: "Chop Steak", ingredients: ["Rindfleisch", "Paprika", "Zwiebel", "Pilze", "Sojasauce", "Ketchup", "Zucker", "Steak-Sauce"] },
	{ name: "Ricotta-Salat", ingredients: ["Ricotta", "Babysalat", "Balsamico-Dressing", "Tomate", "Nüsse"] },
	{ name: "Kartoffel-Jeon", ingredients: ["Kartoffel", "Zwiebel", "Pfannkuchenmehl", "Wasser", "Salz", "Speiseöl"] },
	{ name: "Gebratener Makrele", ingredients: ["Makrele", "Salz", "Pfeffer", "Zitrone", "Speiseöl"] },
	{ name: "Oktopus-Bokkeum", ingredients: ["Oktopus", "Zwiebel", "Frühlingszwiebel", "Kohl", "Gochujang", "Chilipulver", "Knoblauch", "Zucker"] },
	{ name: "Hühnerfuß-Bokkeum", ingredients: ["Hühnerfüße", "Gochujang", "Chilipulver", "Knoblauch", "Zwiebel", "Frühlingszwiebel", "Zucker", "Reissirup"] },
	{ name: "Eis", ingredients: ["Milch", "Zucker", "Eigelb", "Sahne", "Vanille"] },
	{ name: "Tiramisu", ingredients: ["Mascarpone-Käse", "Löffelbiskuits", "Kaffee", "Zucker", "Eigelb", "Kakaopulver"] },
	{ name: "Macaron", ingredients: ["Mandelmehl", "Puderzucker", "Eiweiß", "Zucker", "Lebensmittelfarbe"] },
	{ name: "Croffle", ingredients: ["Croissant-Teig", "Waffeleisen", "Zucker", "Butter"] },
	{ name: "Eierkuchen", ingredients: ["Tarte-Teig", "Ei", "Milch", "Zucker", "Sahne", "Vanilleextrakt"] },
	{ name: "An-Butter-Brot", ingredients: ["Brot", "rote Bohnenpaste", "Butter"] },
	{ name: "Hotteok", ingredients: ["Weizenmehl", "Zucker", "Hefe", "Wasser", "Füllung", "Honig"] },
	{ name: "Bungeoppang", ingredients: ["Weizenmehl", "Ei", "Milch", "Zucker", "rote Bohnenpaste", "Butter"] },
	{ name: "Hot Dog", ingredients: ["Wurst", "Brötchen", "Ketchup", "Senf", "Zwiebel", "Essiggurke"] },
	{ name: "Französische Zwiebelsuppe", ingredients: ["Zwiebel", "Rinderbrühe", "Brot", "Käse", "Butter", "Weizenmehl"] },
	{ name: "Spaghetti mit Fleischbällchen", ingredients: ["Spaghetti", "Hackfleisch vom Rind", "Tomatensauce", "Zwiebel", "Knoblauch", "Paniermehl", "Ei"] },
	{ name: "Fisch-Tacos", ingredients: ["Fisch", "Tortilla", "Kohl", "Salsa", "Limette", "Koriander"] },
	{ name: "Käse-Scones", ingredients: ["Weizenmehl", "Butter", "Milch", "Käse", "Backpulver"] },
	{ name: "Blaubeer-Muffin", ingredients: ["Weizenmehl", "Blaubeeren", "Zucker", "Ei", "Milch", "Öl", "Backpulver"] }
];

window.INGREDIENTS_DB = [
	"Ei", "Hühnchen", "Rindfleisch", "Schweinefleisch", "Zwiebel", "Knoblauch", "Karotte", "Kartoffel", "Spaghetti", "Reis", "Tomate", "Salat",
	"Tofu", "Bohnensprossen", "Erdnüsse", "Rotwein", "Miso", "Algen", "Kimchi", "Speck", "Parmesan", "Sardellen", "Brot",
	"Käse", "Garnele", "Zitronengras", "Galangal", "Limette", "Paprika", "Aubergine", "Zucchini", "Croutons", "Dashi-Brühe",
	"Pancetta", "Pfeffer", "Pilze", "Joghurt", "Weizenmehl", "Zucker", "Salz", "Butter", "Milch", "Sahne", "Gurke",
	"Apfel", "Banane", "Orange", "Zitrone", "Limette", "Brokkoli", "Spinat", "Kürbis", "Süßkartoffel", "Mais", "Erbsen",
	"Kohl", "Sellerie", "Ingwer", "Sojasauce", "Essig", "Olivenöl", "Rapsöl", "Sonnenblumenöl", "Sesamöl",
	"Fischsauce", "Austernsauce", "Hoisin-Sauce", "Ketchup", "Senf", "Mayonnaise", "Basilikum", "Koriander", "Petersilie",
	"Rosmarin", "Thymian", "Salbei", "Minze", "Zimt", "Muskatnuss", "Nelken", "Lorbeerblatt", "Sternanis", "Kardamom",
	"Currypulver", "Chilipulver", "Paprika", "Kurkuma", "Kreuzkümmel", "Koriander", "Dill", "Fenchel", "Vanille",
	"Schokolade", "Kakaopulver", "Marmelade", "Honig", "Ahornsirup", "Melasse", "Erdbeere", "Blaubeere", "Himbeere",
	"Cranberry", "Brombeere", "Ananas", "Mango", "Kiwi", "Trauben", "Birne", "Pfirsich", "Aprikose", "Pflaume", "Dattel",
	"Feige", "Kokosnuss", "Walnüsse", "Mandeln", "Haselnüsse", "Cashewnüsse", "Pistazien", "Macadamia", "Pekannüsse", "Sonnenblumenkerne",
	"Chiasamen", "Kürbiskerne", "Sesam", "Quinoa", "Gerste", "Hirse", "Buchweizen", "Hafer", "Brot", "Nudeln",
	"Nudeln", "Tortilla", "Naan", "Pita-Brot", "Sauerteigbrot", "Bagel", "Croissant", "Donut", "Pizzateig", "Cracker",
	"Wurst", "Salami", "Schinken", "Ente", "Lammfleisch", "Truthahn", "Kaninchen", "Kalb", "Gans", "Sardellen", "Sardine", "Thunfisch",
	"Makrele", "Lachs", "Kabeljau", "Schellfisch", "Seelachs", "Wels", "Tilapia", "Tintenfisch", "Oktopus", "Muscheln", "Miesmuscheln",
	"Jakobsmuscheln", "Hummer", "Krabbe", "Flusskrebs", "Abalone", "Seegurke", "Seeigel", "Wasabi", "Meerrettich",
	"Tabasco", "Sriracha", "Gochujang", "Ssamjang", "Miso", "Miso", "Azukibohnen", "schwarze Bohnen", "Bohnen",
	"Kichererbsen", "Linsen", "grüne Bohnen", "Navy Bohnen", "grüne Bohnen", "Zuckererbsen", "Zuckererbsen", "Edamame", "Mozzarella",
	"Cheddar", "Gouda", "Brie", "Camembert", "Feta", "Blauschimmelkäse", "Schweizer Käse", "Provolone", "Ricotta",
	"Mascarpone", "Frischkäse", "Hüttenkäse", "Sauerrahm", "Joghurt", "Buttermilch", "Kondensmilch",
	"gezuckerte Kondensmilch", "Milchpulver", "Mandelmilch", "Sojamilch", "Reismilch", "Kokosmilch", "Hafermilch",
	"Garnelenpaste", "Sardellenpaste", "Tomatenmark", "Tomatensauce", "Pesto", "Piri-Piri", "Harissa", "Ezbah",
	"Tahini", "Hummus", "Guacamole", "Salsa", "Relish", "Tapenade", "Bratensauce", "Brühe", "Brühe", "Gelatine",
	"Agar-Agar", "Kartoffelstärke", "Kartoffelstärke", "Tapiokastärke", "Kuzu-Stärke", "Reismehl", "Grieß", "Maismehl",
	"Polenta", "Weizenkeime", "Weizenkleie", "Reispapier", "Reispapier für Frühlingsrollen", "Algen", "Reiskuchen", "Udon", "Ramen",
	"Glasnudeln", "Soba", "Fettuccine", "Penne", "Makkaroni", "Lasagne", "Spaghetti", "Linguine", "Engelsnudeln",
	"Gnocchi", "Ravioli", "Tortellini", "Gyoza", "Wonton", "Pierogi", "Empanada", "Tamale", "Frühlingszwiebel",
	"Schalotte", "Lauch", "Rübe", "Radieschen", "Pastinake", "Kohlrübe", "Rote Bete", "Kohlrübe", "Rettich", "Jicama", "Lotuswurzel",
	"Artischocke", "Spargel", "Okra", "Menma", "Eigelb", "Eiweiß", "Wachtelei", "Entenei", "Gänseei",
	"Trüffel", "Morchel", "Steinpilz", "Enoki", "Shiitake", "Austernpilz", "Kräuterseitling", "Champignon", "Portobello",
	"Kastanie", "Wasserkastanie", "Taro", "Yamswurzel", "Maniok", "Haferwurzel", "Topinambur", "Fenchelknolle",
	"Rucola", "Basilikumpesto", "Paprika", "Pak Choi", "Rosenkohl", "Buttermilch", "Kapern",
	"Karamell", "Kümmel", "Cashewkerne", "Chia", "Chiliöl", "Schnittlauch", "Koriandersamen", "Hüttenkäse",
	"Krabbe", "Cranberry", "Sahne", "Brunnenkresse", "Löwenzahn", "Datteln", "Frühlingsrollenblätter", "Farro", "Bockshornklee",
	"Feta-Käse", "Ghee-Butter", "Ziegenkäse", "grüne Bohnen", "Guave", "Haselnüsse", "Hanfsamen", "Kräutermischung",
	"Jackfrucht", "Grünkohl", "Kimchi-Saft", "Kumquat", "Lauch", "Linsennudeln", "Litschi", "Mango-Chutney",
	"Manchego", "Ahornspeck", "Majoran", "Mizuna", "Mönchsfrucht", "Pilzsauce", "Senfkohl",
	"Chinaball", "Nektarine", "Okra", "Oliven", "Orangenschale", "Papaya", "Passionsfrucht", "Erbsensprossen",
	"Pekannüsse", "Pepper Jack", "Kaki", "Pinienkerne", "Pistaziencreme", "Pflaumentomate", "Popcorn", "Prosciutto",
	"Pumpernickel", "Quark", "Radicchio", "Ras el Hanout", "rote Linsen", "Ricotta Salata", "Rucola", "Römersalat",
	"Roquefort", "Rosenwasser", "Kohlrübe", "Sago", "Haferwurzel", "Wirsingkohl", "Schnittlauch", "Schalotten",
	"Shiso", "Seidentofu", "Räucherlachs", "Zuckererbsen", "Zuckererbsen", "Sauerampfer", "Sojaprotein", "Dinkel",
	"Tintenfischtinte", "Stilton", "Nameko", "Sumach", "getrocknete Tomaten", "Zuckermais", "Mangold",
	"Tamarinde", "Tempeh", "Thymian", "gerösteter Sesam", "Yuba", "Tomate", "Trüffelöl", "Rübengrün",
	"Valencia-Orange", "Veganer Käse", "Wild", "Glasnudeln", "Sushi-Reis", "Brunnenkresse", "Weizenmehl",
	"weiße Schokolade", "Wildreis", "Yamswurzel", "Za'atar", "Zeste", "Zucchiniblüten", "Adzukibohne", "Amaranth",
	"Anis", "Bambussprossen", "Bananenpfeffer", "Basilikumsamen", "Babymuscheln", "schwarzer Knoblauch", "Blutorange",
	"Borretsch", "Bresaola", "Kaktus", "Tintenfisch", "Kanarische Melone", "kandierter Ingwer", "Karottenblätter", "Maniokmehl",
	"Sellerie", "Chayote", "Shimeji-Pilze", "Chorizo", "Moltebeere", "Kokosblütenzucker", "Confit-Knoblauch",
	"Feldsalat", "Cranberry-Bohnen", "Cremini", "Dolma", "Edelweiß", "Farn", "Rogen", "Frisée", "Garam Masala",
	"Knoblauch-Schnittlauch", "Goji-Beeren", "goldene Bete", "junger Knoblauch", "Guanciale", "Schweinefüße", "Meerrettichwurzel",
	"Topinambur", "Kaffirlimette", "Süßholzwurzel", "Kelp", "Lardon", "Lavendel", "Limoncello", "lange Bohnen",
	"Lotussamen", "Miso-Karamell", "Mizithra", "Maulbeere", "Muscadine", "Kapuzinerkresse", "Brennnessel", "Okra-Blätter",
	"Olivenbeere", "Pastinakenblätter", "Pattypan-Zucchini", "Pecorino", "Pepino", "Sesamblätter", "eingelegtes Gemüse",
	"Bohnen", "Ananas-Salbei", "rosa Pfeffer", "Pflaumen", "Poblano", "Portulak", "Quitte", "wilder Knoblauch",
	"Rhabarber", "gerösteter Knoblauch", "Romanesco", "Bohnen", "Kohlrübenblätter", "Lachskaviar", "Süßkartoffel", "Meeresspargel",
	"Schinken", "Wurst", "Ramen", "Rettich", "Schnittlauch", "Tintenfisch", "Seeananas", "Wasserkresse", "Taro-Stiele", "Farn", "gesalzene Garnelen",
	"Ginseng", "Jujube", "Klebreis", "Kartoffelstärke", "Rinderdarm", "Sesamblätter", "Brühe", "Reissirup", "Seeteufel", "Sundae",
	"Peperoncino", "Baguette", "Weißwein", "Steak-Sauce", "Babysalat", "Balsamico-Dressing", "Nüsse",
	"Pfannkuchenmehl", "Makrele", "Oktopus", "Kohl", "Hühnerfüße", "Mandelmehl", "Puderzucker", "Lebensmittelfarbe",
	"Croissant-Teig", "Waffeleisen", "Tarte-Teig", "Vanilleextrakt", "rote Bohnenpaste", "Hefe", "Füllung", "Honig", "rote Bohnenpaste",
	"Wurst", "Öl", "Backpulver"
];