const flags = [
  { country: "Afghanistan", img: "https://flagcdn.com/af.svg" },
  { country: "Åland Islands", img: "https://flagcdn.com/ax.svg" },
  { country: "Albania", img: "https://flagcdn.com/al.svg" },
  { country: "Algeria", img: "https://flagcdn.com/dz.svg" },
  { country: "American Samoa", img: "https://flagcdn.com/as.svg" },
  { country: "Andorra", img: "https://flagcdn.com/ad.svg" },
  { country: "Angola", img: "https://flagcdn.com/ao.svg" },
  { country: "Anguilla", img: "https://flagcdn.com/ai.svg" },
  { country: "Antarctica", img: "https://flagcdn.com/aq.svg" },
  { country: "Antigua and Barbuda", img: "https://flagcdn.com/ag.svg" },
  { country: "Argentina", img: "https://flagcdn.com/ar.svg" },
  { country: "Armenia", img: "https://flagcdn.com/am.svg" },
  { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
  { country: "Australia", img: "https://flagcdn.com/au.svg" },
  { country: "Austria", img: "https://flagcdn.com/at.svg" },
  { country: "Azerbaijan", img: "https://flagcdn.com/az.svg" },
  { country: "Bahamas", img: "https://flagcdn.com/bs.svg" },
  { country: "Bahrain", img: "https://flagcdn.com/bh.svg" },
  { country: "Bangladesh", img: "https://flagcdn.com/bd.svg" },
  { country: "Barbados", img: "https://flagcdn.com/bb.svg" },
  { country: "Belarus", img: "https://flagcdn.com/by.svg" },
  { country: "Belgium", img: "https://flagcdn.com/be.svg" },
  { country: "Belize", img: "https://flagcdn.com/bz.svg" },
  { country: "Benin", img: "https://flagcdn.com/bj.svg" },
  { country: "Bermuda", img: "https://flagcdn.com/bm.svg" },
  { country: "Bhutan", img: "https://flagcdn.com/bt.svg" },
  { country: "Bolivia", img: "https://flagcdn.com/bo.svg" },
  { country: "Caribbean Netherlands", img: "https://flagcdn.com/bq.svg" },
  { country: "Bosnia and Herzegovina", img: "https://flagcdn.com/ba.svg" },
  { country: "Botswana", img: "https://flagcdn.com/bw.svg" },
  { country: "Bouvet Island", img: "https://flagcdn.com/bv.svg" },
  { country: "Brazil", img: "https://flagcdn.com/br.svg" },
  { country: "British Indian Ocean Territory", img: "https://flagcdn.com/io.svg" },
  { country: "British Virgin Islands", img: "https://flagcdn.com/vg.svg" },
  { country: "Brunei", img: "https://flagcdn.com/bn.svg" },
  { country: "Bulgaria", img: "https://flagcdn.com/bg.svg" },
  { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
  { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
  { country: "Cabo Verde", img: "https://flagcdn.com/cv.svg" },
  { country: "Cambodia", img: "https://flagcdn.com/kh.svg" },
  { country: "Cameroon", img: "https://flagcdn.com/cm.svg" },
  { country: "Canada", img: "https://flagcdn.com/ca.svg" },
  { country: "Cayman Islands", img: "https://flagcdn.com/ky.svg" },
  { country: "Central African Republic", img: "https://flagcdn.com/cf.svg" },
  { country: "Chad", img: "https://flagcdn.com/td.svg" },
  { country: "Chile", img: "https://flagcdn.com/cl.svg" },
  { country: "China", img: "https://flagcdn.com/cn.svg" },
  { country: "Christmas Island", img: "https://flagcdn.com/cx.svg" },
  { country: "Cocos (Keeling) Islands", img: "https://flagcdn.com/cc.svg" },
  { country: "Colombia", img: "https://flagcdn.com/co.svg" },
  { country: "Comoros", img: "https://flagcdn.com/km.svg" },
  { country: "Congo (DRC)", img: "https://flagcdn.com/cd.svg" },
  { country: "Congo (Republic)", img: "https://flagcdn.com/cg.svg" },
  { country: "Cook Islands", img: "https://flagcdn.com/ck.svg" },
  { country: "Costa Rica", img: "https://flagcdn.com/cr.svg" },
  { country: "Côte d'Ivoire", img: "https://flagcdn.com/ci.svg" },
  { country: "Croatia", img: "https://flagcdn.com/hr.svg" },
  { country: "Cuba", img: "https://flagcdn.com/cu.svg" },
  { country: "Curaçao", img: "https://flagcdn.com/cw.svg" },
  { country: "Cyprus", img: "https://flagcdn.com/cy.svg" },
  { country: "Czechia", img: "https://flagcdn.com/cz.svg" },
  { country: "Denmark", img: "https://flagcdn.com/dk.svg" },
  { country: "Djibouti", img: "https://flagcdn.com/dj.svg" },
  { country: "Dominica", img: "https://flagcdn.com/dm.svg" },
  { country: "Dominican Republic", img: "https://flagcdn.com/do.svg" },
  { country: "Ecuador", img: "https://flagcdn.com/ec.svg" },
  { country: "Egypt", img: "https://flagcdn.com/eg.svg" },
  { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
  { country: "Equatorial Guinea", img: "https://flagcdn.com/gq.svg" },
  { country: "Eritrea", img: "https://flagcdn.com/er.svg" },
  { country: "Estonia", img: "https://flagcdn.com/ee.svg" },
  { country: "Eswatini", img: "https://flagcdn.com/sz.svg" },
  { country: "Ethiopia", img: "https://flagcdn.com/et.svg" },
  { country: "Falkland Islands", img: "https://flagcdn.com/fk.svg" },
  { country: "Faroe Islands", img: "https://flagcdn.com/fo.svg" },
  { country: "Fiji", img: "https://flagcdn.com/fj.svg" },
  { country: "Finland", img: "https://flagcdn.com/fi.svg" },
  { country: "France", img: "https://flagcdn.com/fr.svg" },
  { country: "French Guiana", img: "https://flagcdn.com/gf.svg" },
  { country: "French Polynesia", img: "https://flagcdn.com/pf.svg" },
  { country: "French Southern Territories", img: "https://flagcdn.com/tf.svg" },
  { country: "Gabon", img: "https://flagcdn.com/ga.svg" },
  { country: "Gambia", img: "https://flagcdn.com/gm.svg" },
  { country: "Georgia", img: "https://flagcdn.com/ge.svg" },
  { country: "Germany", img: "https://flagcdn.com/de.svg" },
  { country: "Ghana", img: "https://flagcdn.com/gh.svg" },
  { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
  { country: "Greece", img: "https://flagcdn.com/gr.svg" },
  { country: "Greenland", img: "https://flagcdn.com/gl.svg" },
  { country: "Grenada", img: "https://flagcdn.com/gd.svg" },
  { country: "Guadeloupe", img: "https://flagcdn.com/gp.svg" },
  { country: "Guam", img: "https://flagcdn.com/gu.svg" },
  { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
  { country: "Guernsey", img: "https://flagcdn.com/gg.svg" },
  { country: "Guinea", img: "https://flagcdn.com/gn.svg" },
  { country: "Guinea-Bissau", img: "https://flagcdn.com/gw.svg" },
  { country: "Guyana", img: "https://flagcdn.com/gy.svg" },
  { country: "Haiti", img: "https://flagcdn.com/ht.svg" },
  { country: "Heard Island and McDonald Islands", img: "https://flagcdn.com/hm.svg" },
  { country: "Vatican City", img: "https://flagcdn.com/va.svg" },
  { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
  { country: "Hong Kong", img: "https://flagcdn.com/hk.svg" },
  { country: "Hungary", img: "https://flagcdn.com/hu.svg" },
  { country: "Iceland", img: "https://flagcdn.com/is.svg" },
  { country: "India", img: "https://flagcdn.com/in.svg" },
  { country: "Indonesia", img: "https://flagcdn.com/id.svg" },
  { country: "Iran", img: "https://flagcdn.com/ir.svg" },
  { country: "Iraq", img: "https://flagcdn.com/iq.svg" },
  { country: "Ireland", img: "https://flagcdn.com/ie.svg" },
  { country: "Isle of Man", img: "https://flagcdn.com/im.svg" },
  { country: "Israel", img: "https://flagcdn.com/il.svg" },
  { country: "Italy", img: "https://flagcdn.com/it.svg" },
  { country: "Jamaica", img: "https://flagcdn.com/jm.svg" },
  { country: "Japan", img: "https://flagcdn.com/jp.svg" },
  { country: "Jersey", img: "https://flagcdn.com/je.svg" },
  { country: "Jordan", img: "https://flagcdn.com/jo.svg" },
  { country: "Kazakhstan", img: "https://flagcdn.com/kz.svg" },
  { country: "Kenya", img: "https://flagcdn.com/ke.svg" },
  { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
  { country: "North Korea", img: "https://flagcdn.com/kp.svg" },
  { country: "South Korea", img: "https://flagcdn.com/kr.svg" },
  { country: "Kuwait", img: "https://flagcdn.com/kw.svg" },
  { country: "Kyrgyzstan", img: "https://flagcdn.com/kg.svg" },
  { country: "Laos", img: "https://flagcdn.com/la.svg" },
  { country: "Latvia", img: "https://flagcdn.com/lv.svg" },
  { country: "Lebanon", img: "https://flagcdn.com/lb.svg" },
  { country: "Lesotho", img: "https://flagcdn.com/ls.svg" },
  { country: "Liberia", img: "https://flagcdn.com/lr.svg" },
  { country: "Libya", img: "https://flagcdn.com/ly.svg" },
  { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
  { country: "Lithuania", img: "https://flagcdn.com/lt.svg" },
  { country: "Luxembourg", img: "https://flagcdn.com/lu.svg" },
  { country: "Macao", img: "https://flagcdn.com/mo.svg" },
  { country: "Madagascar", img: "https://flagcdn.com/mg.svg" },
  { country: "Malawi", img: "https://flagcdn.com/mw.svg" },
  { country: "Malaysia", img: "https://flagcdn.com/my.svg" },
  { country: "Maldives", img: "https://flagcdn.com/mv.svg" },
  { country: "Mali", img: "https://flagcdn.com/ml.svg" },
  { country: "Malta", img: "https://flagcdn.com/mt.svg" },
  { country: "Marshall Islands", img: "https://flagcdn.com/mh.svg" },
  { country: "Martinique", img: "https://flagcdn.com/mq.svg" },
  { country: "Mauritania", img: "https://flagcdn.com/mr.svg" },
  { country: "Mauritius", img: "https://flagcdn.com/mu.svg" },
  { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
  { country: "Mexico", img: "https://flagcdn.com/mx.svg" },
  { country: "Micronesia", img: "https://flagcdn.com/fm.svg" },
  { country: "Moldova", img: "https://flagcdn.com/md.svg" },
  { country: "Monaco", img: "https://flagcdn.com/mc.svg" },
  { country: "Mongolia", img: "https://flagcdn.com/mn.svg" },
  { country: "Montenegro", img: "https://flagcdn.com/me.svg" },
  { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
  { country: "Morocco", img: "https://flagcdn.com/ma.svg" },
  { country: "Mozambique", img: "https://flagcdn.com/mz.svg" },
  { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
  { country: "Namibia", img: "https://flagcdn.com/na.svg" },
  { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
  { country: "Nepal", img: "https://flagcdn.com/np.svg" },
  { country: "Netherlands", img: "https://flagcdn.com/nl.svg" },
  { country: "New Caledonia", img: "https://flagcdn.com/nc.svg" },
  { country: "New Zealand", img: "https://flagcdn.com/nz.svg" },
  { country: "Nicaragua", img: "https://flagcdn.com/ni.svg" },
  { country: "Niger", img: "https://flagcdn.com/ne.svg" },
  { country: "Nigeria", img: "https://flagcdn.com/ng.svg" },
  { country: "Niue", img: "https://flagcdn.com/nu.svg" },
  { country: "Norfolk Island", img: "https://flagcdn.com/nf.svg" },
  { country: "Northern Mariana Islands", img: "https://flagcdn.com/mp.svg" },
  { country: "Norway", img: "https://flagcdn.com/no.svg" },
  { country: "Oman", img: "https://flagcdn.com/om.svg" },
  { country: "Pakistan", img: "https://flagcdn.com/pk.svg" },
  { country: "Palau", img: "https://flagcdn.com/pw.svg" },
  { country: "Palestine", img: "https://flagcdn.com/ps.svg" },
  { country: "Panama", img: "https://flagcdn.com/pa.svg" },
  { country: "Papua New Guinea", img: "https://flagcdn.com/pg.svg" },
  { country: "Paraguay", img: "https://flagcdn.com/py.svg" },
  { country: "Peru", img: "https://flagcdn.com/pe.svg" },
  { country: "Philippines", img: "https://flagcdn.com/ph.svg" },
  { country: "Pitcairn Islands", img: "https://flagcdn.com/pn.svg" },
  { country: "Poland", img: "https://flagcdn.com/pl.svg" },
  { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
  { country: "Puerto Rico", img: "https://flagcdn.com/pr.svg" },
  { country: "Qatar", img: "https://flagcdn.com/qa.svg" },
  { country: "Réunion", img: "https://flagcdn.com/re.svg" },
  { country: "Romania", img: "https://flagcdn.com/ro.svg" },
  { country: "Russia", img: "https://flagcdn.com/ru.svg" },
  { country: "Rwanda", img: "https://flagcdn.com/rw.svg" },
  { country: "Saint Barthélemy", img: "https://flagcdn.com/bl.svg" },
  { country: "Saint Helena", img: "https://flagcdn.com/sh.svg" },
  { country: "Saint Kitts and Nevis", img: "https://flagcdn.com/kn.svg" },
  { country: "Saint Lucia", img: "https://flagcdn.com/lc.svg" },
  { country: "Saint Martin", img: "https://flagcdn.com/mf.svg" },
  { country: "Saint Pierre and Miquelon", img: "https://flagcdn.com/pm.svg" },
  { country: "Saint Vincent and the Grenadines", img: "https://flagcdn.com/vc.svg" },
  { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
  { country: "San Marino", img: "https://flagcdn.com/sm.svg" },
  { country: "São Tomé and Príncipe", img: "https://flagcdn.com/st.svg" },
  { country: "Saudi Arabia", img: "https://flagcdn.com/sa.svg" },
  { country: "Senegal", img: "https://flagcdn.com/sn.svg" },
  { country: "Serbia", img: "https://flagcdn.com/rs.svg" },
  { country: "Seychelles", img: "https://flagcdn.com/sc.svg" },
  { country: "Sierra Leone", img: "https://flagcdn.com/sl.svg" },
  { country: "Singapore", img: "https://flagcdn.com/sg.svg" },
  { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
  { country: "Slovakia", img: "https://flagcdn.com/sk.svg" },
  { country: "Slovenia", img: "https://flagcdn.com/si.svg" },
  { country: "Solomon Islands", img: "https://flagcdn.com/sb.svg" },
  { country: "Somalia", img: "https://flagcdn.com/so.svg" },
  { country: "South Africa", img: "https://flagcdn.com/za.svg" },
  { country: "South Georgia", img: "https://flagcdn.com/gs.svg" },
  { country: "South Sudan", img: "https://flagcdn.com/ss.svg" },
  { country: "Spain", img: "https://flagcdn.com/es.svg" },
  { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
  { country: "Sudan", img: "https://flagcdn.com/sd.svg" },
  { country: "Suriname", img: "https://flagcdn.com/sr.svg" },
  { country: "Svalbard and Jan Mayen", img: "https://flagcdn.com/sj.svg" },
  { country: "Sweden", img: "https://flagcdn.com/se.svg" },
  { country: "Switzerland", img: "https://flagcdn.com/ch.svg" },
  { country: "Syria", img: "https://flagcdn.com/sy.svg" },
  { country: "Taiwan", img: "https://flagcdn.com/tw.svg" },
  { country: "Tajikistan", img: "https://flagcdn.com/tj.svg" },
  { country: "Tanzania", img: "https://flagcdn.com/tz.svg" },
  { country: "Thailand", img: "https://flagcdn.com/th.svg" },
  { country: "Timor-Leste", img: "https://flagcdn.com/tl.svg" },
  { country: "Togo", img: "https://flagcdn.com/tg.svg" },
  { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
  { country: "Tonga", img: "https://flagcdn.com/to.svg" },
  { country: "Trinidad and Tobago", img: "https://flagcdn.com/tt.svg" },
  { country: "Tunisia", img: "https://flagcdn.com/tn.svg" },
  { country: "Turkey", img: "https://flagcdn.com/tr.svg" },
  { country: "Turkmenistan", img: "https://flagcdn.com/tm.svg" },
  { country: "Turks and Caicos Islands", img: "https://flagcdn.com/tc.svg" },
  { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
  { country: "Uganda", img: "https://flagcdn.com/ug.svg" },
  { country: "Ukraine", img: "https://flagcdn.com/ua.svg" },
  { country: "United Arab Emirates", img: "https://flagcdn.com/ae.svg" },
  { country: "United Kingdom", img: "https://flagcdn.com/gb.svg" },
  { country: "United States", img: "https://flagcdn.com/us.svg" },
  { country: "U.S. Outlying Islands", img: "https://flagcdn.com/um.svg" },
  { country: "Uruguay", img: "https://flagcdn.com/uy.svg" },
  { country: "Uzbekistan", img: "https://flagcdn.com/uz.svg" },
  { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
  { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
  { country: "Vietnam", img: "https://flagcdn.com/vn.svg" },
  { country: "Wallis and Futuna", img: "https://flagcdn.com/wf.svg" },
  { country: "Western Sahara", img: "https://flagcdn.com/eh.svg" },
  { country: "Yemen", img: "https://flagcdn.com/ye.svg" },
  { country: "Zambia", img: "https://flagcdn.com/zm.svg" },
  { country: "Zimbabwe", img: "https://flagcdn.com/zw.svg" },
  { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
