const flags = [
    { country: "أفغانستان", img: "https://flagcdn.com/af.svg" },
    { country: "جزر آلاند", img: "https://flagcdn.com/ax.svg" },
    { country: "ألبانيا", img: "https://flagcdn.com/al.svg" },
    { country: "الجزائر", img: "https://flagcdn.com/dz.svg" },
    { country: "ساموا الأمريكية", img: "https://flagcdn.com/as.svg" },
    { country: "أندورا", img: "https://flagcdn.com/ad.svg" },
    { country: "أنغولا", img: "https://flagcdn.com/ao.svg" },
    { country: "أنغيلا", img: "https://flagcdn.com/ai.svg" },
    { country: "أنتاركتيكا", img: "https://flagcdn.com/aq.svg" },
    { country: "أنتيغوا وباربودا", img: "https://flagcdn.com/ag.svg" },
    { country: "الأرجنتين", img: "https://flagcdn.com/ar.svg" },
    { country: "أرمينيا", img: "https://flagcdn.com/am.svg" },
    { country: "أروبا", img: "https://flagcdn.com/aw.svg" },
    { country: "أستراليا", img: "https://flagcdn.com/au.svg" },
    { country: "النمسا", img: "https://flagcdn.com/at.svg" },
    { country: "أذربيجان", img: "https://flagcdn.com/az.svg" },
    { country: "جزر البهاما", img: "https://flagcdn.com/bs.svg" },
    { country: "البحرين", img: "https://flagcdn.com/bh.svg" },
    { country: "بنغلاديش", img: "https://flagcdn.com/bd.svg" },
    { country: "باربادوس", img: "https://flagcdn.com/bb.svg" },
    { country: "بيلاروسيا", img: "https://flagcdn.com/by.svg" },
    { country: "بلجيكا", img: "https://flagcdn.com/be.svg" },
    { country: "بليز", img: "https://flagcdn.com/bz.svg" },
    { country: "بنين", img: "https://flagcdn.com/bj.svg" },
    { country: "برمودا", img: "https://flagcdn.com/bm.svg" },
    { country: "بوتان", img: "https://flagcdn.com/bt.svg" },
    { country: "بوليفيا", img: "https://flagcdn.com/bo.svg" },
    { country: "جزر الكاريبي الهولندية", img: "https://flagcdn.com/bq.svg" },
    { country: "البوسنة والهرسك", img: "https://flagcdn.com/ba.svg" },
    { country: "بوتسوانا", img: "https://flagcdn.com/bw.svg" },
    { country: "جزيرة بوفيت", img: "https://flagcdn.com/bv.svg" },
    { country: "البرازيل", img: "https://flagcdn.com/br.svg" },
    { country: "إقليم المحيط الهندي البريطاني", img: "https://flagcdn.com/io.svg" },
    { country: "جزر فيرجن البريطانية", img: "https://flagcdn.com/vg.svg" },
    { country: "بروناي", img: "https://flagcdn.com/bn.svg" },
    { country: "بلغاريا", img: "https://flagcdn.com/bg.svg" },
    { country: "بوركينا فاسو", img: "https://flagcdn.com/bf.svg" },
    { country: "بوروندي", img: "https://flagcdn.com/bi.svg" },
    { country: "الرأس الأخضر", img: "https://flagcdn.com/cv.svg" },
    { country: "كمبوديا", img: "https://flagcdn.com/kh.svg" },
    { country: "الكاميرون", img: "https://flagcdn.com/cm.svg" },
    { country: "كندا", img: "https://flagcdn.com/ca.svg" },
    { country: "جزر كايمان", img: "https://flagcdn.com/ky.svg" },
    { country: "جمهورية أفريقيا الوسطى", img: "https://flagcdn.com/cf.svg" },
    { country: "تشاد", img: "https://flagcdn.com/td.svg" },
    { country: "تشيلي", img: "https://flagcdn.com/cl.svg" },
    { country: "الصين", img: "https://flagcdn.com/cn.svg" },
    { country: "جزيرة كريسماس", img: "https://flagcdn.com/cx.svg" },
    { country: "جزر كوكوس (كيلينغ)", img: "https://flagcdn.com/cc.svg" },
    { country: "كولومبيا", img: "https://flagcdn.com/co.svg" },
    { country: "جزر القمر", img: "https://flagcdn.com/km.svg" },
    { country: "جمهورية الكونغو الديمقراطية", img: "https://flagcdn.com/cd.svg" },
    { country: "جمهورية الكونغو", img: "https://flagcdn.com/cg.svg" },
    { country: "جزر كوك", img: "https://flagcdn.com/ck.svg" },
    { country: "كوستاريكا", img: "https://flagcdn.com/cr.svg" },
    { country: "ساحل العاج", img: "https://flagcdn.com/ci.svg" },
    { country: "كرواتيا", img: "https://flagcdn.com/hr.svg" },
    { country: "كوبا", img: "https://flagcdn.com/cu.svg" },
    { country: "كوراساو", img: "https://flagcdn.com/cw.svg" },
    { country: "قبرص", img: "https://flagcdn.com/cy.svg" },
    { country: "التشيك", img: "https://flagcdn.com/cz.svg" },
    { country: "الدنمارك", img: "https://flagcdn.com/dk.svg" },
    { country: "جيبوتي", img: "https://flagcdn.com/dj.svg" },
    { country: "دومينيكا", img: "https://flagcdn.com/dm.svg" },
    { country: "جمهورية الدومينيكان", img: "https://flagcdn.com/do.svg" },
    { country: "الإكوادور", img: "https://flagcdn.com/ec.svg" },
    { country: "مصر", img: "https://flagcdn.com/eg.svg" },
    { country: "السلفادور", img: "https://flagcdn.com/sv.svg" },
    { country: "غينيا الاستوائية", img: "https://flagcdn.com/gq.svg" },
    { country: "إريتريا", img: "https://flagcdn.com/er.svg" },
    { country: "إستونيا", img: "https://flagcdn.com/ee.svg" },
    { country: "إسواتيني", img: "https://flagcdn.com/sz.svg" },
    { country: "إثيوبيا", img: "https://flagcdn.com/et.svg" },
    { country: "جزر فوكلاند", img: "https://flagcdn.com/fk.svg" },
    { country: "جزر فارو", img: "https://flagcdn.com/fo.svg" },
    { country: "فيجي", img: "https://flagcdn.com/fj.svg" },
    { country: "فنلندا", img: "https://flagcdn.com/fi.svg" },
    { country: "فرنسا", img: "https://flagcdn.com/fr.svg" },
    { country: "غويانا الفرنسية", img: "https://flagcdn.com/gf.svg" },
    { country: "بولينيزيا الفرنسية", img: "https://flagcdn.com/pf.svg" },
    { country: "الأراضي الجنوبية والقطبية الفرنسية", img: "https://flagcdn.com/tf.svg" },
    { country: "الغابون", img: "https://flagcdn.com/ga.svg" },
    { country: "غامبيا", img: "https://flagcdn.com/gm.svg" },
    { country: "جورجيا", img: "https://flagcdn.com/ge.svg" },
    { country: "ألمانيا", img: "https://flagcdn.com/de.svg" },
    { country: "غانا", img: "https://flagcdn.com/gh.svg" },
    { country: "جبل طارق", img: "https://flagcdn.com/gi.svg" },
    { country: "اليونان", img: "https://flagcdn.com/gr.svg" },
    { country: "غرينلاند", img: "https://flagcdn.com/gl.svg" },
    { country: "غرينادا", img: "https://flagcdn.com/gd.svg" },
    { country: "غوادلوب", img: "https://flagcdn.com/gp.svg" },
    { country: "غوام", img: "https://flagcdn.com/gu.svg" },
    { country: "غواتيمالا", img: "https://flagcdn.com/gt.svg" },
    { country: "غيرنزي", img: "https://flagcdn.com/gg.svg" },
    { country: "غينيا", img: "https://flagcdn.com/gn.svg" },
    { country: "غينيا بيساو", img: "https://flagcdn.com/gw.svg" },
    { country: "غيانا", img: "https://flagcdn.com/gy.svg" },
    { country: "هايتي", img: "https://flagcdn.com/ht.svg" },
    { country: "جزيرة هيرد وجزر ماكدونالد", img: "https://flagcdn.com/hm.svg" },
    { country: "الفاتيكان", img: "https://flagcdn.com/va.svg" },
    { country: "هندوراس", img: "https://flagcdn.com/hn.svg" },
    { country: "هونغ كونغ", img: "https://flagcdn.com/hk.svg" },
    { country: "المجر", img: "https://flagcdn.com/hu.svg" },
    { country: "أيسلندا", img: "https://flagcdn.com/is.svg" },
    { country: "الهند", img: "https://flagcdn.com/in.svg" },
    { country: "إندونيسيا", img: "https://flagcdn.com/id.svg" },
    { country: "إيران", img: "https://flagcdn.com/ir.svg" },
    { country: "العراق", img: "https://flagcdn.com/iq.svg" },
    { country: "أيرلندا", img: "https://flagcdn.com/ie.svg" },
    { country: "جزيرة مان", img: "https://flagcdn.com/im.svg" },
    { country: "إسرائيل", img: "https://flagcdn.com/il.svg" },
    { country: "إيطاليا", img: "https://flagcdn.com/it.svg" },
    { country: "جامايكا", img: "https://flagcdn.com/jm.svg" },
    { country: "اليابان", img: "https://flagcdn.com/jp.svg" },
    { country: "جيرسي", img: "https://flagcdn.com/je.svg" },
    { country: "الأردن", img: "https://flagcdn.com/jo.svg" },
    { country: "كازاخستان", img: "https://flagcdn.com/kz.svg" },
    { country: "كينيا", img: "https://flagcdn.com/ke.svg" },
    { country: "كيريباتي", img: "https://flagcdn.com/ki.svg" },
    { country: "كوريا الشمالية", img: "https://flagcdn.com/kp.svg" },
    { country: "كوريا الجنوبية", img: "https://flagcdn.com/kr.svg" },
    { country: "الكويت", img: "https://flagcdn.com/kw.svg" },
    { country: "قيرغيزستان", img: "https://flagcdn.com/kg.svg" },
    { country: "لاوس", img: "https://flagcdn.com/la.svg" },
    { country: "لاتفيا", img: "https://flagcdn.com/lv.svg" },
    { country: "لبنان", img: "https://flagcdn.com/lb.svg" },
    { country: "ليسوتو", img: "https://flagcdn.com/ls.svg" },
    { country: "ليبيريا", img: "https://flagcdn.com/lr.svg" },
    { country: "ليبيا", img: "https://flagcdn.com/ly.svg" },
    { country: "ليختنشتاين", img: "https://flagcdn.com/li.svg" },
    { country: "ليتوانيا", img: "https://flagcdn.com/lt.svg" },
    { country: "لوكسمبورغ", img: "https://flagcdn.com/lu.svg" },
    { country: "ماكاو", img: "https://flagcdn.com/mo.svg" },
    { country: "مدغشقر", img: "https://flagcdn.com/mg.svg" },
    { country: "مالاوي", img: "https://flagcdn.com/mw.svg" },
    { country: "ماليزيا", img: "https://flagcdn.com/my.svg" },
    { country: "جزر المالديف", img: "https://flagcdn.com/mv.svg" },
    { country: "مالي", img: "https://flagcdn.com/ml.svg" },
    { country: "مالطا", img: "https://flagcdn.com/mt.svg" },
    { country: "جزر مارشال", img: "https://flagcdn.com/mh.svg" },
    { country: "مارتينيك", img: "https://flagcdn.com/mq.svg" },
    { country: "موريتانيا", img: "https://flagcdn.com/mr.svg" },
    { country: "موريشيوس", img: "https://flagcdn.com/mu.svg" },
    { country: "مايوت", img: "https://flagcdn.com/yt.svg" },
    { country: "المكسيك", img: "https://flagcdn.com/mx.svg" },
    { country: "ميكرونيزيا", img: "https://flagcdn.com/fm.svg" },
    { country: "مولدوفا", img: "https://flagcdn.com/md.svg" },
    { country: "موناكو", img: "https://flagcdn.com/mc.svg" },
    { country: "منغوليا", img: "https://flagcdn.com/mn.svg" },
    { country: "الجبل الأسود", img: "https://flagcdn.com/me.svg" },
    { country: "مونتسيرات", img: "https://flagcdn.com/ms.svg" },
    { country: "المغرب", img: "https://flagcdn.com/ma.svg" },
    { country: "موزمبيق", img: "https://flagcdn.com/mz.svg" },
    { country: "ميانمار", img: "https://flagcdn.com/mm.svg" },
    { country: "ناميبيا", img: "https://flagcdn.com/na.svg" },
    { country: "ناورو", img: "https://flagcdn.com/nr.svg" },
    { country: "نيبال", img: "https://flagcdn.com/np.svg" },
    { country: "هولندا", img: "https://flagcdn.com/nl.svg" },
    { country: "كاليدونيا الجديدة", img: "https://flagcdn.com/nc.svg" },
    { country: "نيوزيلندا", img: "https://flagcdn.com/nz.svg" },
    { country: "نيكاراغوا", img: "https://flagcdn.com/ni.svg" },
    { country: "النيجر", img: "https://flagcdn.com/ne.svg" },
    { country: "نيجيريا", img: "https://flagcdn.com/ng.svg" },
    { country: "نيوي", img: "https://flagcdn.com/nu.svg" },
    { country: "جزيرة نورفولك", img: "https://flagcdn.com/nf.svg" },
    { country: "جزر ماريانا الشمالية", img: "https://flagcdn.com/mp.svg" },
    { country: "النرويج", img: "https://flagcdn.com/no.svg" },
    { country: "عمان", img: "https://flagcdn.com/om.svg" },
    { country: "باكستان", img: "https://flagcdn.com/pk.svg" },
    { country: "بالاو", img: "https://flagcdn.com/pw.svg" },
    { country: "فلسطين", img: "https://flagcdn.com/ps.svg" },
    { country: "بنما", img: "https://flagcdn.com/pa.svg" },
    { country: "بابوا غينيا الجديدة", img: "https://flagcdn.com/pg.svg" },
    { country: "باراغواي", img: "https://flagcdn.com/py.svg" },
    { country: "بيرو", img: "https://flagcdn.com/pe.svg" },
    { country: "الفلبين", img: "https://flagcdn.com/ph.svg" },
    { country: "جزر بيتكيرن", img: "https://flagcdn.com/pn.svg" },
    { country: "بولندا", img: "https://flagcdn.com/pl.svg" },
    { country: "البرتغال", img: "https://flagcdn.com/pt.svg" },
    { country: "بورتوريكو", img: "https://flagcdn.com/pr.svg" },
    { country: "قطر", img: "https://flagcdn.com/qa.svg" },
    { country: "ريونيون", img: "https://flagcdn.com/re.svg" },
    { country: "رومانيا", img: "https://flagcdn.com/ro.svg" },
    { country: "روسيا", img: "https://flagcdn.com/ru.svg" },
    { country: "رواندا", img: "https://flagcdn.com/rw.svg" },
    { country: "سانت بارتيليمي", img: "https://flagcdn.com/bl.svg" },
    { country: "سانت هيلينا", img: "https://flagcdn.com/sh.svg" },
    { country: "سانت كيتس ونيفيس", img: "https://flagcdn.com/kn.svg" },
    { country: "سانت لوسيا", img: "https://flagcdn.com/lc.svg" },
    { country: "سانت مارتن (الجانب الفرنسي)", img: "https://flagcdn.com/mf.svg" },
    { country: "سان بيير وميكلون", img: "https://flagcdn.com/pm.svg" },
    { country: "سانت فنسنت والغرينادين", img: "https://flagcdn.com/vc.svg" },
    { country: "ساموا", img: "https://flagcdn.com/ws.svg" },
    { country: "سان مارينو", img: "https://flagcdn.com/sm.svg" },
    { country: "ساو تومي وبرينسيبي", img: "https://flagcdn.com/st.svg" },
    { country: "المملكة العربية السعودية", img: "https://flagcdn.com/sa.svg" },
    { country: "السنغال", img: "https://flagcdn.com/sn.svg" },
    { country: "صربيا", img: "https://flagcdn.com/rs.svg" },
    { country: "سيشل", img: "https://flagcdn.com/sc.svg" },
    { country: "سيراليون", img: "https://flagcdn.com/sl.svg" },
    { country: "سنغافورة", img: "https://flagcdn.com/sg.svg" },
    { country: "سينت مارتن (الجانب الهولندي)", img: "https://flagcdn.com/sx.svg" },
    { country: "سلوفاكيا", img: "https://flagcdn.com/sk.svg" },
    { country: "سلوفينيا", img: "https://flagcdn.com/si.svg" },
    { country: "جزر سليمان", img: "https://flagcdn.com/sb.svg" },
    { country: "الصومال", img: "https://flagcdn.com/so.svg" },
    { country: "جنوب أفريقيا", img: "https://flagcdn.com/za.svg" },
    { country: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", img: "https://flagcdn.com/gs.svg" },
    { country: "جنوب السودان", img: "https://flagcdn.com/ss.svg" },
    { country: "إسبانيا", img: "https://flagcdn.com/es.svg" },
    { country: "سريلانكا", img: "https://flagcdn.com/lk.svg" },
    { country: "السودان", img: "https://flagcdn.com/sd.svg" },
    { country: "سورينام", img: "https://flagcdn.com/sr.svg" },
    { country: "سفالبارد ويان ماين", img: "https://flagcdn.com/sj.svg" },
    { country: "السويد", img: "https://flagcdn.com/se.svg" },
    { country: "سويسرا", img: "https://flagcdn.com/ch.svg" },
    { country: "سوريا", img: "https://flagcdn.com/sy.svg" },
    { country: "تايوان", img: "https://flagcdn.com/tw.svg" },
    { country: "طاجيكستان", img: "https://flagcdn.com/tj.svg" },
    { country: "تنزانيا", img: "https://flagcdn.com/tz.svg" },
    { country: "تايلاند", img: "https://flagcdn.com/th.svg" },
    { country: "تيمور الشرقية", img: "https://flagcdn.com/tl.svg" },
    { country: "توغو", img: "https://flagcdn.com/tg.svg" },
    { country: "توكيلاو", img: "https://flagcdn.com/tk.svg" },
    { country: "تونغا", img: "https://flagcdn.com/to.svg" },
    { country: "ترينيداد وتوباغو", img: "https://flagcdn.com/tt.svg" },
    { country: "تونس", img: "https://flagcdn.com/tn.svg" },
    { country: "تركيا", img: "https://flagcdn.com/tr.svg" },
    { country: "تركمانستان", img: "https://flagcdn.com/tm.svg" },
    { country: "جزر تركس وكايكوس", img: "https://flagcdn.com/tc.svg" },
    { country: "توفالو", img: "https://flagcdn.com/tv.svg" },
    { country: "أوغندا", img: "https://flagcdn.com/ug.svg" },
    { country: "أوكرانيا", img: "https://flagcdn.com/ua.svg" },
    { country: "الإمارات العربية المتحدة", img: "https://flagcdn.com/ae.svg" },
    { country: "المملكة المتحدة", img: "https://flagcdn.com/gb.svg" },
    { country: "الولايات المتحدة", img: "https://flagcdn.com/us.svg" },
    { country: "جزر الولايات المتحدة النائية الصغيرة", img: "https://flagcdn.com/um.svg" },
    { country: "الأوروغواي", img: "https://flagcdn.com/uy.svg" },
    { country: "أوزبكستان", img: "https://flagcdn.com/uz.svg" },
    { country: "فانواتو", img: "https://flagcdn.com/vu.svg" },
    { country: "فنزويلا", img: "https://flagcdn.com/ve.svg" },
    { country: "فيتنام", img: "https://flagcdn.com/vn.svg" },
    { country: "واليس وفوتونا", img: "https://flagcdn.com/wf.svg" },
    { country: "الصحراء الغربية", img: "https://flagcdn.com/eh.svg" },
    { country: "اليمن", img: "https://flagcdn.com/ye.svg" },
    { country: "زامبيا", img: "https://flagcdn.com/zm.svg" },
    { country: "زيمبابوي", img: "https://flagcdn.com/zw.svg" },
    { country: "كوسوفو", img: "https://flagcdn.com/xk.svg" }
];